theme: jekyll-theme-cayman
title: Autodesk Machine Control Framework
description: 'Middleware framework to integrate CAD/CAM software with machine hardware systems into a production-ready, complete and cohesive closed loop system.'
