/*++

Copyright (C) 2020 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++ implementation file in order to allow easy
development of MC Driver Environment Interface. The functions in this file need to be implemented. It needs to be generated only once.

Interface version: 1.0.0

*/

#include "libmcdriverenv_abi.hpp"
#include "libmcdriverenv_interfaces.hpp"
#include "libmcdriverenv_interfaceexception.hpp"

#include <map>

using namespace LibMCDriverEnv::Impl;

LibMCDriverEnvResult handleLibMCDriverEnvException(IBase * pIBaseClass, ELibMCDriverEnvInterfaceException & Exception)
{
	LibMCDriverEnvResult errorCode = Exception.getErrorCode();

	if (pIBaseClass != nullptr)
		pIBaseClass->RegisterErrorMessage(Exception.what());

	return errorCode;
}

LibMCDriverEnvResult handleStdException(IBase * pIBaseClass, std::exception & Exception)
{
	LibMCDriverEnvResult errorCode = LIBMCDRIVERENV_ERROR_GENERICEXCEPTION;

	if (pIBaseClass != nullptr)
		pIBaseClass->RegisterErrorMessage(Exception.what());

	return errorCode;
}

LibMCDriverEnvResult handleUnhandledException(IBase * pIBaseClass)
{
	LibMCDriverEnvResult errorCode = LIBMCDRIVERENV_ERROR_GENERICEXCEPTION;

	if (pIBaseClass != nullptr)
		pIBaseClass->RegisterErrorMessage("Unhandled Exception");

	return errorCode;
}



/*************************************************************************************************************************
 Class implementation for Base
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class implementation for DriverEnvironment
**************************************************************************************************************************/


/*************************************************************************************************************************
 Function table lookup implementation
**************************************************************************************************************************/

LibMCDriverEnvResult LibMCDriverEnv::Impl::LibMCDriverEnv_GetProcAddress (const char * pProcName, void ** ppProcAddress)
{
	if (pProcName == nullptr)
		return LIBMCDRIVERENV_ERROR_INVALIDPARAM;
	if (ppProcAddress == nullptr)
		return LIBMCDRIVERENV_ERROR_INVALIDPARAM;
	*ppProcAddress = nullptr;
	std::string sProcName (pProcName);
	
	if (sProcName == "libmcdriverenv_getversion") 
		*ppProcAddress = (void*) &libmcdriverenv_getversion;
	if (sProcName == "libmcdriverenv_getlasterror") 
		*ppProcAddress = (void*) &libmcdriverenv_getlasterror;
	if (sProcName == "libmcdriverenv_releaseinstance") 
		*ppProcAddress = (void*) &libmcdriverenv_releaseinstance;
	if (sProcName == "libmcdriverenv_acquireinstance") 
		*ppProcAddress = (void*) &libmcdriverenv_acquireinstance;
	if (sProcName == "libmcdriverenv_getsymbollookupmethod") 
		*ppProcAddress = (void*) &libmcdriverenv_getsymbollookupmethod;
	
	if (*ppProcAddress == nullptr) 
		return LIBMCDRIVERENV_ERROR_COULDNOTFINDLIBRARYEXPORT;
	return LIBMCDRIVERENV_SUCCESS;
}

/*************************************************************************************************************************
 Global functions implementation
**************************************************************************************************************************/
LibMCDriverEnvResult libmcdriverenv_getversion(LibMCDriverEnv_uint32 * pMajor, LibMCDriverEnv_uint32 * pMinor, LibMCDriverEnv_uint32 * pMicro)
{
	IBase* pIBaseClass = nullptr;

	try {
		if (!pMajor)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDPARAM);
		if (!pMinor)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDPARAM);
		if (!pMicro)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDPARAM);
		CWrapper::GetVersion(*pMajor, *pMinor, *pMicro);

		return LIBMCDRIVERENV_SUCCESS;
	}
	catch (ELibMCDriverEnvInterfaceException & Exception) {
		return handleLibMCDriverEnvException(pIBaseClass, Exception);
	}
	catch (std::exception & StdException) {
		return handleStdException(pIBaseClass, StdException);
	}
	catch (...) {
		return handleUnhandledException(pIBaseClass);
	}
}

LibMCDriverEnvResult libmcdriverenv_getlasterror(LibMCDriverEnv_Base pInstance, const LibMCDriverEnv_uint32 nErrorMessageBufferSize, LibMCDriverEnv_uint32* pErrorMessageNeededChars, char * pErrorMessageBuffer, bool * pHasError)
{
	IBase* pIBaseClass = nullptr;

	try {
		if ( (!pErrorMessageBuffer) && !(pErrorMessageNeededChars) )
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDPARAM);
		if (pHasError == nullptr)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDPARAM);
		IBase* pIBaseClassInstance = (IBase *)pInstance;
		IBase* pIInstance = dynamic_cast<IBase*>(pIBaseClassInstance);
		if (!pIInstance)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDCAST);
		
		std::string sErrorMessage("");
		*pHasError = CWrapper::GetLastError(pIInstance, sErrorMessage);

		if (pErrorMessageNeededChars)
			*pErrorMessageNeededChars = (LibMCDriverEnv_uint32) (sErrorMessage.size()+1);
		if (pErrorMessageBuffer) {
			if (sErrorMessage.size() >= nErrorMessageBufferSize)
				throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_BUFFERTOOSMALL);
			for (size_t iErrorMessage = 0; iErrorMessage < sErrorMessage.size(); iErrorMessage++)
				pErrorMessageBuffer[iErrorMessage] = sErrorMessage[iErrorMessage];
			pErrorMessageBuffer[sErrorMessage.size()] = 0;
		}
		return LIBMCDRIVERENV_SUCCESS;
	}
	catch (ELibMCDriverEnvInterfaceException & Exception) {
		return handleLibMCDriverEnvException(pIBaseClass, Exception);
	}
	catch (std::exception & StdException) {
		return handleStdException(pIBaseClass, StdException);
	}
	catch (...) {
		return handleUnhandledException(pIBaseClass);
	}
}

LibMCDriverEnvResult libmcdriverenv_releaseinstance(LibMCDriverEnv_Base pInstance)
{
	IBase* pIBaseClass = nullptr;

	try {
		IBase* pIBaseClassInstance = (IBase *)pInstance;
		IBase* pIInstance = dynamic_cast<IBase*>(pIBaseClassInstance);
		if (!pIInstance)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDCAST);
		
		CWrapper::ReleaseInstance(pIInstance);

		return LIBMCDRIVERENV_SUCCESS;
	}
	catch (ELibMCDriverEnvInterfaceException & Exception) {
		return handleLibMCDriverEnvException(pIBaseClass, Exception);
	}
	catch (std::exception & StdException) {
		return handleStdException(pIBaseClass, StdException);
	}
	catch (...) {
		return handleUnhandledException(pIBaseClass);
	}
}

LibMCDriverEnvResult libmcdriverenv_acquireinstance(LibMCDriverEnv_Base pInstance)
{
	IBase* pIBaseClass = nullptr;

	try {
		IBase* pIBaseClassInstance = (IBase *)pInstance;
		IBase* pIInstance = dynamic_cast<IBase*>(pIBaseClassInstance);
		if (!pIInstance)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDCAST);
		
		CWrapper::AcquireInstance(pIInstance);

		return LIBMCDRIVERENV_SUCCESS;
	}
	catch (ELibMCDriverEnvInterfaceException & Exception) {
		return handleLibMCDriverEnvException(pIBaseClass, Exception);
	}
	catch (std::exception & StdException) {
		return handleStdException(pIBaseClass, StdException);
	}
	catch (...) {
		return handleUnhandledException(pIBaseClass);
	}
}

LibMCDriverEnvResult libmcdriverenv_getsymbollookupmethod(LibMCDriverEnv_pvoid * pSymbolLookupMethod)
{
	IBase* pIBaseClass = nullptr;

	try {
		if (pSymbolLookupMethod == nullptr)
			throw ELibMCDriverEnvInterfaceException (LIBMCDRIVERENV_ERROR_INVALIDPARAM);
		*pSymbolLookupMethod = (void*)&LibMCDriverEnv::Impl::LibMCDriverEnv_GetProcAddress;
		return LIBMCDRIVERENV_SUCCESS;
	}
	catch (ELibMCDriverEnvInterfaceException & Exception) {
		return handleLibMCDriverEnvException(pIBaseClass, Exception);
	}
	catch (std::exception & StdException) {
		return handleStdException(pIBaseClass, StdException);
	}
	catch (...) {
		return handleUnhandledException(pIBaseClass);
	}
}


