name: 'Build Linux x64'
description: 'Build binaries for Linux x64'
inputs:
  buildscript:  # id of input
    description: 'Path to the build script to run'
    required: true
    default: './build_clean.sh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.buildscript }}