/*++

Copyright (C) 2020 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated C++ header file in order to allow easy
development of MC Driver Euler. The implementer of MC Driver Euler needs to
derive concrete classes from the abstract classes in this header.

Interface version: 2.0.0

*/


#ifndef __LIBMCDRIVER_EULER_CPPINTERFACES
#define __LIBMCDRIVER_EULER_CPPINTERFACES

#include <string>
#include <memory>

#include "libmcdriver_euler_types.hpp"


#include "libmcenv_dynamic.hpp"

namespace LibMCDriver_Euler {
namespace Impl {

/**
 Forward declarations of class interfaces
*/
class IBase;
class IDriver;
class IEulerConnection;
class IDriver_Euler;



/*************************************************************************************************************************
 Parameter Cache definitions
**************************************************************************************************************************/

class ParameterCache {
	public:
		virtual ~ParameterCache() {}
};

template <class T1> class ParameterCache_1 : public ParameterCache {
	private:
		T1 m_param1;
	public:
		ParameterCache_1 (const T1 & param1)
			: m_param1 (param1)
		{
		}

		void retrieveData (T1 & param1)
		{
			param1 = m_param1;
		}
};

template <class T1, class T2> class ParameterCache_2 : public ParameterCache {
	private:
		T1 m_param1;
		T2 m_param2;
	public:
		ParameterCache_2 (const T1 & param1, const T2 & param2)
			: m_param1 (param1), m_param2 (param2)
		{
		}

		void retrieveData (T1 & param1, T2 & param2)
		{
			param1 = m_param1;
			param2 = m_param2;
		}
};

template <class T1, class T2, class T3> class ParameterCache_3 : public ParameterCache {
	private:
		T1 m_param1;
		T2 m_param2;
		T3 m_param3;
	public:
		ParameterCache_3 (const T1 & param1, const T2 & param2, const T3 & param3)
			: m_param1 (param1), m_param2 (param2), m_param3 (param3)
		{
		}

		void retrieveData (T1 & param1, T2 & param2, T3 & param3)
		{
			param1 = m_param1;
			param2 = m_param2;
			param3 = m_param3;
		}
};

template <class T1, class T2, class T3, class T4> class ParameterCache_4 : public ParameterCache {
	private:
		T1 m_param1;
		T2 m_param2;
		T3 m_param3;
		T4 m_param4;
	public:
		ParameterCache_4 (const T1 & param1, const T2 & param2, const T3 & param3, const T4 & param4)
			: m_param1 (param1), m_param2 (param2), m_param3 (param3), m_param4 (param4)
		{
		}

		void retrieveData (T1 & param1, T2 & param2, T3 & param3, T4 & param4)
		{
			param1 = m_param1;
			param2 = m_param2;
			param3 = m_param3;
			param4 = m_param4;
		}
};


/*************************************************************************************************************************
 Class interface for Base 
**************************************************************************************************************************/

class IBase {
private:
	std::unique_ptr<ParameterCache> m_ParameterCache;
public:
	/**
	* IBase::~IBase - virtual destructor of IBase
	*/
	virtual ~IBase() {};

	/**
	* IBase::ReleaseBaseClassInterface - Releases ownership of a base class interface. Deletes the reference, if necessary.
	* @param[in] pIBase - The base class instance to release
	*/
	static void ReleaseBaseClassInterface(IBase* pIBase)
	{
		if (pIBase) {
			pIBase->DecRefCount();
		}
	};

	/**
	* IBase::AcquireBaseClassInterface - Acquires shared ownership of a base class interface.
	* @param[in] pIBase - The base class instance to acquire
	*/
	static void AcquireBaseClassInterface(IBase* pIBase)
	{
		if (pIBase) {
			pIBase->IncRefCount();
		}
	};


	/**
	* IBase::GetLastErrorMessage - Returns the last error registered of this class instance
	* @param[out] sErrorMessage - Message of the last error registered
	* @return Has an error been registered already
	*/
	virtual bool GetLastErrorMessage(std::string & sErrorMessage) = 0;

	/**
	* IBase::ClearErrorMessages - Clears all registered messages of this class instance
	*/
	virtual void ClearErrorMessages() = 0;

	/**
	* IBase::RegisterErrorMessage - Registers an error message with this class instance
	* @param[in] sErrorMessage - Error message to register
	*/
	virtual void RegisterErrorMessage(const std::string & sErrorMessage) = 0;

	/**
	* IBase::IncRefCount - Increases the reference count of a class instance
	*/
	virtual void IncRefCount() = 0;

	/**
	* IBase::DecRefCount - Decreases the reference count of a class instance and free releases it, if the last reference has been removed
	* @return Has the object been released
	*/
	virtual bool DecRefCount() = 0;

	/**
	* IBase::_setCache - set parameter cache of object
	*/
	void _setCache(ParameterCache * pCache)
	{
		m_ParameterCache.reset(pCache);
	}

	/**
	* IBase::_getCache - returns parameter cache of object
	*/
	ParameterCache* _getCache()
	{
		return m_ParameterCache.get();
	}

};


/**
 Definition of a shared pointer class for IBase
*/
template<class T>
class IBaseSharedPtr : public std::shared_ptr<T>
{
public:
	explicit IBaseSharedPtr(T* t = nullptr)
		: std::shared_ptr<T>(t, IBase::ReleaseBaseClassInterface)
	{
		t->IncRefCount();
	}

	// Reset function, as it also needs to properly set the deleter.
	void reset(T* t = nullptr)
	{
		std::shared_ptr<T>::reset(t, IBase::ReleaseBaseClassInterface);
	}

	// Get-function that increases the Base class's reference count
	T* getCoOwningPtr()
	{
		T* t = this->get();
		t->IncRefCount();
		return t;
	}
};


typedef IBaseSharedPtr<IBase> PIBase;


/*************************************************************************************************************************
 Class interface for Driver 
**************************************************************************************************************************/

class IDriver : public virtual IBase {
public:
	/**
	* IDriver::Configure - Configures a driver with its specific configuration data.
	* @param[in] sConfigurationString - Configuration data of driver.
	*/
	virtual void Configure(const std::string & sConfigurationString) = 0;

	/**
	* IDriver::GetName - returns the name identifier of the driver
	* @return Name of the driver.
	*/
	virtual std::string GetName() = 0;

	/**
	* IDriver::GetType - returns the type identifier of the driver
	* @return Type of the driver.
	*/
	virtual std::string GetType() = 0;

	/**
	* IDriver::GetVersion - returns the version identifiers of the driver
	* @param[out] nMajor - Major version.
	* @param[out] nMinor - Minor version.
	* @param[out] nMicro - Micro version.
	* @param[out] sBuild - Build identifier.
	*/
	virtual void GetVersion(LibMCDriver_Euler_uint32 & nMajor, LibMCDriver_Euler_uint32 & nMinor, LibMCDriver_Euler_uint32 & nMicro, std::string & sBuild) = 0;

	/**
	* IDriver::QueryParameters - Updates the driver parameters in the driver environment. Should only be called in the driver thread.
	*/
	virtual void QueryParameters() = 0;

	/**
	* IDriver::QueryParametersEx - Updates the driver parameters in the driver environment. Might be called out of thread. Implementation MUST be able to handle parallel calls.
	* @param[in] pDriverUpdateInstance - Status update instance.
	*/
	virtual void QueryParametersEx(LibMCEnv::PDriverStatusUpdateSession pDriverUpdateInstance) = 0;

};

typedef IBaseSharedPtr<IDriver> PIDriver;


/*************************************************************************************************************************
 Class interface for EulerConnection 
**************************************************************************************************************************/

class IEulerConnection : public virtual IBase {
public:
	/**
	* IEulerConnection::Disconnect - Disconnects the connection. No further call can be handled after.
	*/
	virtual void Disconnect() = 0;

	/**
	* IEulerConnection::GetIdentifier - Returns the connection identifier.
	* @return Identifier of the connection.
	*/
	virtual std::string GetIdentifier() = 0;

	/**
	* IEulerConnection::GetApplicationName - Returns the application name.
	* @return Application Name in use.
	*/
	virtual std::string GetApplicationName() = 0;

	/**
	* IEulerConnection::GetApplicationVersion - Returns the application version.
	* @return Application Version in use.
	*/
	virtual std::string GetApplicationVersion() = 0;

	/**
	* IEulerConnection::GetBaseURL - Returns the base URL.
	* @return Base URL in use.
	*/
	virtual std::string GetBaseURL() = 0;

	/**
	* IEulerConnection::GetAPIKey - Returns the API Key.
	* @return API Key in use.
	*/
	virtual std::string GetAPIKey() = 0;

	/**
	* IEulerConnection::GetDeviceID - Returns the DeviceID.
	* @return DeviceID in use.
	*/
	virtual std::string GetDeviceID() = 0;

	/**
	* IEulerConnection::StartHeartBeat - Starts the heartbeat.
	*/
	virtual void StartHeartBeat() = 0;

	/**
	* IEulerConnection::StopHeartBeat - Stops the heartbeat.
	*/
	virtual void StopHeartBeat() = 0;

	/**
	* IEulerConnection::CreateBuild - Creates a new build job.
	* @param[in] sJobName - BuildJob Name
	* @param[in] nLayerCount - Layer Count
	* @return New BuildJob ID
	*/
	virtual std::string CreateBuild(const std::string & sJobName, const LibMCDriver_Euler_uint32 nLayerCount) = 0;

	/**
	* IEulerConnection::UploadImage - Uploads an image to a build job.
	* @param[in] sBuildJobID - BuildJob ID
	* @param[in] nLayerIndex - Layer Index
	* @param[in] eImageType - Image Type
	* @param[in] pImage - Image Instance
	*/
	virtual void UploadImage(const std::string & sBuildJobID, const LibMCDriver_Euler_uint32 nLayerIndex, const LibMCDriver_Euler::eEulerImageType eImageType, LibMCEnv::PImageData pImage) = 0;

	/**
	* IEulerConnection::SetJobStatus - Updates a Job's status
	* @param[in] sBuildJobID - BuildJob ID
	* @param[in] eJobStatus - New Job Status
	*/
	virtual void SetJobStatus(const std::string & sBuildJobID, const LibMCDriver_Euler::eEulerJobStatus eJobStatus) = 0;

};

typedef IBaseSharedPtr<IEulerConnection> PIEulerConnection;


/*************************************************************************************************************************
 Class interface for Driver_Euler 
**************************************************************************************************************************/

class IDriver_Euler : public virtual IDriver {
public:
	/**
	* IDriver_Euler::SetCustomSDKResource - Sets the machine resource name of the LibEuler SDK to load. MUST be called before Connect or it has no effect.
	* @param[in] sResourceName - Resource name of core machine package. Empty means standard naming applies.
	*/
	virtual void SetCustomSDKResource(const std::string & sResourceName) = 0;

	/**
	* IDriver_Euler::SetApplicationDetails - Sets the application details. Will be used for subsequent connections.
	* @param[in] sApplicationName - Application Name to use.
	* @param[in] sApplicationVersion - Application Version to use.
	*/
	virtual void SetApplicationDetails(const std::string & sApplicationName, const std::string & sApplicationVersion) = 0;

	/**
	* IDriver_Euler::Connect - Creates a Euler Connection.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @param[in] sBaseURL - BaseURL to use.
	* @param[in] sAPIKey - API Key to use.
	* @param[in] sDeviceID - Device ID to use.
	* @return Euler Connection Instance.
	*/
	virtual IEulerConnection * Connect(const std::string & sIdentifier, const std::string & sBaseURL, const std::string & sAPIKey, const std::string & sDeviceID) = 0;

	/**
	* IDriver_Euler::ConnectWithLicenseData - Creates a Euler Connection from a license file data.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @param[in] nLicenseDataBufferSize - Number of elements in buffer
	* @param[in] pLicenseDataBuffer - License Data file to use.
	* @param[in] sDeviceID - Device ID to use.
	* @return Euler Connection Instance.
	*/
	virtual IEulerConnection * ConnectWithLicenseData(const std::string & sIdentifier, const LibMCDriver_Euler_uint64 nLicenseDataBufferSize, const LibMCDriver_Euler_uint8 * pLicenseDataBuffer, const std::string & sDeviceID) = 0;

	/**
	* IDriver_Euler::ConnectWithLicenseResource - Creates a Euler Connection from a license file resource.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @param[in] sLicenseResourceName - License Data resource to use.
	* @param[in] sDeviceID - Device ID to use.
	* @return Euler Connection Instance.
	*/
	virtual IEulerConnection * ConnectWithLicenseResource(const std::string & sIdentifier, const std::string & sLicenseResourceName, const std::string & sDeviceID) = 0;

	/**
	* IDriver_Euler::FindConnection - Finds a connection. Fails if connection does not exist.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @return Euler Connection Instance.
	*/
	virtual IEulerConnection * FindConnection(const std::string & sIdentifier) = 0;

	/**
	* IDriver_Euler::ConnectionExists - Checks if a connection exists with a certain identifier.
	* @param[in] sIdentifier - Identifier for the connection.
	* @return Returns true, if the connection exists, false otherwise.
	*/
	virtual bool ConnectionExists(const std::string & sIdentifier) = 0;

	/**
	* IDriver_Euler::CloseAllConnections - Closes all connections.
	*/
	virtual void CloseAllConnections() = 0;

};

typedef IBaseSharedPtr<IDriver_Euler> PIDriver_Euler;


/*************************************************************************************************************************
 Global functions declarations
**************************************************************************************************************************/
class CWrapper {
public:
	// Injected Components
	static LibMCEnv::PWrapper sPLibMCEnvWrapper;

	/**
	* Ilibmcdriver_euler::GetVersion - retrieves the binary version of this library.
	* @param[out] nMajor - returns the major version of this library
	* @param[out] nMinor - returns the minor version of this library
	* @param[out] nMicro - returns the micro version of this library
	*/
	static void GetVersion(LibMCDriver_Euler_uint32 & nMajor, LibMCDriver_Euler_uint32 & nMinor, LibMCDriver_Euler_uint32 & nMicro);

	/**
	* Ilibmcdriver_euler::GetLastError - Returns the last error recorded on this object
	* @param[in] pInstance - Instance Handle
	* @param[out] sErrorMessage - Message of the last error
	* @return Is there a last error to query
	*/
	static bool GetLastError(IBase* pInstance, std::string & sErrorMessage);

	/**
	* Ilibmcdriver_euler::ReleaseInstance - Releases shared ownership of an Instance
	* @param[in] pInstance - Instance Handle
	*/
	static void ReleaseInstance(IBase* pInstance);

	/**
	* Ilibmcdriver_euler::AcquireInstance - Acquires shared ownership of an Instance
	* @param[in] pInstance - Instance Handle
	*/
	static void AcquireInstance(IBase* pInstance);

	/**
	* Ilibmcdriver_euler::CreateDriver - Creates a driver instance with a specific name.
	* @param[in] sName - Name of driver to be created.
	* @param[in] sType - Type of driver to be created.
	* @param[in] pDriverEnvironment - Environment of this driver.
	* @return New Driver instance
	*/
	static IDriver * CreateDriver(const std::string & sName, const std::string & sType, LibMCEnv::PDriverEnvironment pDriverEnvironment);

};

LibMCDriver_EulerResult LibMCDriver_Euler_GetProcAddress (const char * pProcName, void ** ppProcAddress);

} // namespace Impl
} // namespace LibMCDriver_Euler

#endif // __LIBMCDRIVER_EULER_CPPINTERFACES
