/*++

Copyright (C) 2023 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated C++ implementation file in order to allow easy
development of MC Driver ScanLab SCANmotionControl. It needs to be generated only once.

Interface version: 2.0.0

*/

#include "libmcdriver_scanlabsmc_abi.hpp"
#include "libmcdriver_scanlabsmc_interfaces.hpp"
#include "libmcdriver_scanlabsmc_interfaceexception.hpp"
#include "libmcdriver_scanlabsmc_driver_scanlabsmc.hpp"

using namespace LibMCDriver_ScanLabSMC;
using namespace LibMCDriver_ScanLabSMC::Impl;

// Injected Components
LibMCEnv::PWrapper CWrapper::sPLibMCEnvWrapper;

void CWrapper::GetVersion(LibMCDriver_ScanLabSMC_uint32 & nMajor, LibMCDriver_ScanLabSMC_uint32 & nMinor, LibMCDriver_ScanLabSMC_uint32 & nMicro)
{
	nMajor = LIBMCDRIVER_SCANLABSMC_VERSION_MAJOR;
	nMinor = LIBMCDRIVER_SCANLABSMC_VERSION_MINOR;
	nMicro = LIBMCDRIVER_SCANLABSMC_VERSION_MICRO;
}

bool CWrapper::GetLastError(IBase* pInstance, std::string & sErrorMessage)
{
	if (pInstance) {
		return pInstance->GetLastErrorMessage (sErrorMessage);
	} else {
		return false;
	}
}

void CWrapper::ReleaseInstance(IBase* pInstance)
{
	IBase::ReleaseBaseClassInterface(pInstance);
}

void CWrapper::AcquireInstance(IBase* pInstance)
{
	IBase::AcquireBaseClassInterface(pInstance);
}

IDriver * CWrapper::CreateDriver(const std::string & sName, const std::string & sType, LibMCEnv::PDriverEnvironment pDriverEnvironment)
{
	if (sType == "scanlab-smc-0.6")
		return new CDriver_ScanLabSMC(sName, sType, pDriverEnvironment);

	return nullptr;
}

#ifdef _MSC_VER
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_driver_configure")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_driver_getname")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_driver_gettype")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_driver_getversion")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_driver_queryparametersex")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_getversion")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_getlasterror")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_releaseinstance")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_acquireinstance")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_injectcomponent")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_createdriver")
#pragma comment(linker, "/export:libmcdriver_scanlabsmc_getsymbollookupmethod")

#pragma comment(linker, "/export:libmcdriver_driver_configure=libmcdriver_scanlabsmc_driver_configure")
#pragma comment(linker, "/export:libmcdriver_driver_getname=libmcdriver_scanlabsmc_driver_getname")
#pragma comment(linker, "/export:libmcdriver_driver_gettype=libmcdriver_scanlabsmc_driver_gettype")
#pragma comment(linker, "/export:libmcdriver_driver_getversion=libmcdriver_scanlabsmc_driver_getversion")
#pragma comment(linker, "/export:libmcdriver_driver_queryparametersex=libmcdriver_scanlabsmc_driver_queryparametersex")
#pragma comment(linker, "/export:libmcdriver_getversion=libmcdriver_scanlabsmc_getversion")
#pragma comment(linker, "/export:libmcdriver_getlasterror=libmcdriver_scanlabsmc_getlasterror")
#pragma comment(linker, "/export:libmcdriver_releaseinstance=libmcdriver_scanlabsmc_releaseinstance")
#pragma comment(linker, "/export:libmcdriver_acquireinstance=libmcdriver_scanlabsmc_acquireinstance")
#pragma comment(linker, "/export:libmcdriver_injectcomponent=libmcdriver_scanlabsmc_injectcomponent")
#pragma comment(linker, "/export:libmcdriver_createdriver=libmcdriver_scanlabsmc_createdriver")
#pragma comment(linker, "/export:libmcdriver_getsymbollookupmethod=libmcdriver_scanlabsmc_getsymbollookupmethod")

#endif

#ifdef __GNUC__
void libmcdriver_driver_configure (void) __attribute__((alias("libmcdriver_scanlabsmc_driver_configure")));
void libmcdriver_driver_getname (void) __attribute__((alias("libmcdriver_scanlabsmc_driver_getname")));
void libmcdriver_driver_gettype(void) __attribute__((alias("libmcdriver_scanlabsmc_driver_gettype")));
void libmcdriver_driver_getversion(void) __attribute__((alias("libmcdriver_scanlabsmc_driver_getversion")));
void libmcdriver_driver_queryparametersex(void) __attribute__((alias("libmcdriver_scanlabsmc_driver_queryparametersex")));
void libmcdriver_getversion(void) __attribute__((alias("libmcdriver_scanlabsmc_getversion")));
void libmcdriver_getlasterror(void) __attribute__((alias("libmcdriver_scanlabsmc_getlasterror")));
void libmcdriver_releaseinstance(void) __attribute__((alias("libmcdriver_scanlabsmc_releaseinstance")));
void libmcdriver_acquireinstance(void) __attribute__((alias("libmcdriver_scanlabsmc_acquireinstance")));
void libmcdriver_injectcomponent(void) __attribute__((alias("libmcdriver_scanlabsmc_injectcomponent")));
void libmcdriver_createdriver(void) __attribute__((alias("libmcdriver_scanlabsmc_createdriver")));
void libmcdriver_getsymbollookupmethod(void) __attribute__((alias("libmcdriver_scanlabsmc_getsymbollookupmethod")));


#endif