/*++

Copyright (C) 2023 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated C++-Header file with basic types in
order to allow an easy use of MC Driver cifX

Interface version: 1.0.0

*/

#ifndef __LIBMCDRIVER_CIFX_TYPES_HEADER_CPP
#define __LIBMCDRIVER_CIFX_TYPES_HEADER_CPP


/*************************************************************************************************************************
 Scalar types definition
**************************************************************************************************************************/

#ifdef LIBMCDRIVER_CIFX_USELEGACYINTEGERTYPES

typedef unsigned char LibMCDriver_CifX_uint8;
typedef unsigned short LibMCDriver_CifX_uint16 ;
typedef unsigned int LibMCDriver_CifX_uint32;
typedef unsigned long long LibMCDriver_CifX_uint64;
typedef char LibMCDriver_CifX_int8;
typedef short LibMCDriver_CifX_int16;
typedef int LibMCDriver_CifX_int32;
typedef long long LibMCDriver_CifX_int64;

#else // LIBMCDRIVER_CIFX_USELEGACYINTEGERTYPES

#include <stdint.h>

typedef uint8_t LibMCDriver_CifX_uint8;
typedef uint16_t LibMCDriver_CifX_uint16;
typedef uint32_t LibMCDriver_CifX_uint32;
typedef uint64_t LibMCDriver_CifX_uint64;
typedef int8_t LibMCDriver_CifX_int8;
typedef int16_t LibMCDriver_CifX_int16;
typedef int32_t LibMCDriver_CifX_int32;
typedef int64_t LibMCDriver_CifX_int64 ;

#endif // LIBMCDRIVER_CIFX_USELEGACYINTEGERTYPES

typedef float LibMCDriver_CifX_single;
typedef double LibMCDriver_CifX_double;

/*************************************************************************************************************************
 General type definitions
**************************************************************************************************************************/

typedef LibMCDriver_CifX_int32 LibMCDriver_CifXResult;
typedef void * LibMCDriver_CifXHandle;
typedef void * LibMCDriver_CifX_pvoid;

/*************************************************************************************************************************
 Version for LibMCDriver_CifX
**************************************************************************************************************************/

#define LIBMCDRIVER_CIFX_VERSION_MAJOR 1
#define LIBMCDRIVER_CIFX_VERSION_MINOR 0
#define LIBMCDRIVER_CIFX_VERSION_MICRO 0
#define LIBMCDRIVER_CIFX_VERSION_PRERELEASEINFO ""
#define LIBMCDRIVER_CIFX_VERSION_BUILDINFO ""

/*************************************************************************************************************************
 Error constants for LibMCDriver_CifX
**************************************************************************************************************************/

#define LIBMCDRIVER_CIFX_SUCCESS 0
#define LIBMCDRIVER_CIFX_ERROR_NOTIMPLEMENTED 1 /** functionality not implemented */
#define LIBMCDRIVER_CIFX_ERROR_INVALIDPARAM 2 /** an invalid parameter was passed */
#define LIBMCDRIVER_CIFX_ERROR_INVALIDCAST 3 /** a type cast failed */
#define LIBMCDRIVER_CIFX_ERROR_BUFFERTOOSMALL 4 /** a provided buffer is too small */
#define LIBMCDRIVER_CIFX_ERROR_GENERICEXCEPTION 5 /** a generic exception occurred */
#define LIBMCDRIVER_CIFX_ERROR_COULDNOTLOADLIBRARY 6 /** the library could not be loaded */
#define LIBMCDRIVER_CIFX_ERROR_COULDNOTFINDLIBRARYEXPORT 7 /** a required exported symbol could not be found in the library */
#define LIBMCDRIVER_CIFX_ERROR_INCOMPATIBLEBINARYVERSION 8 /** the version of the binary interface does not match the bindings interface */
#define LIBMCDRIVER_CIFX_ERROR_DRIVERERROR 1000 /** a driver error occured */
#define LIBMCDRIVER_CIFX_ERROR_DRIVERNOTINITIALISED 1001 /** the driver is not initialised */
#define LIBMCDRIVER_CIFX_ERROR_DRIVERNOTCONNECTED 1002 /** the driver is not connected */
#define LIBMCDRIVER_CIFX_ERROR_DRIVERTYPENOTFOUND 1003 /** the driver type has not been found */

/*************************************************************************************************************************
 Error strings for LibMCDriver_CifX
**************************************************************************************************************************/

inline const char * LIBMCDRIVER_CIFX_GETERRORSTRING (LibMCDriver_CifXResult nErrorCode) {
  switch (nErrorCode) {
    case LIBMCDRIVER_CIFX_SUCCESS: return "no error";
    case LIBMCDRIVER_CIFX_ERROR_NOTIMPLEMENTED: return "functionality not implemented";
    case LIBMCDRIVER_CIFX_ERROR_INVALIDPARAM: return "an invalid parameter was passed";
    case LIBMCDRIVER_CIFX_ERROR_INVALIDCAST: return "a type cast failed";
    case LIBMCDRIVER_CIFX_ERROR_BUFFERTOOSMALL: return "a provided buffer is too small";
    case LIBMCDRIVER_CIFX_ERROR_GENERICEXCEPTION: return "a generic exception occurred";
    case LIBMCDRIVER_CIFX_ERROR_COULDNOTLOADLIBRARY: return "the library could not be loaded";
    case LIBMCDRIVER_CIFX_ERROR_COULDNOTFINDLIBRARYEXPORT: return "a required exported symbol could not be found in the library";
    case LIBMCDRIVER_CIFX_ERROR_INCOMPATIBLEBINARYVERSION: return "the version of the binary interface does not match the bindings interface";
    case LIBMCDRIVER_CIFX_ERROR_DRIVERERROR: return "a driver error occured";
    case LIBMCDRIVER_CIFX_ERROR_DRIVERNOTINITIALISED: return "the driver is not initialised";
    case LIBMCDRIVER_CIFX_ERROR_DRIVERNOTCONNECTED: return "the driver is not connected";
    case LIBMCDRIVER_CIFX_ERROR_DRIVERTYPENOTFOUND: return "the driver type has not been found";
    default: return "unknown error";
  }
}

/*************************************************************************************************************************
 Declaration of handle classes 
**************************************************************************************************************************/

typedef LibMCDriver_CifXHandle LibMCDriver_CifX_Base;
typedef LibMCDriver_CifXHandle LibMCDriver_CifX_Driver;
typedef LibMCDriver_CifXHandle LibMCDriver_CifX_BoardInformation;
typedef LibMCDriver_CifXHandle LibMCDriver_CifX_Driver_CifX;

namespace LibMCDriver_CifX {

} // namespace LibMCDriver_CifX;

// define legacy C-names for enums, structs and function types

#endif // __LIBMCDRIVER_CIFX_TYPES_HEADER_CPP
