/*++

Copyright (C) 2021 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated plain C Header file in order to allow an easy
 use of Autodesk Machine Control Framework SDK

Interface version: 1.0.0

*/

#include "libamcf_types.h"
#include "libamcf_dynamic.h"
#ifdef _WIN32
#include <windows.h>
#else // _WIN32
#include <dlfcn.h>
#include <stdlib.h>
#endif // _WIN32

LibAMCFResult InitLibAMCFWrapperTable(sLibAMCFDynamicWrapperTable * pWrapperTable)
{
	if (pWrapperTable == NULL)
		return LIBAMCF_ERROR_INVALIDPARAM;
	
	pWrapperTable->m_LibraryHandle = NULL;
	pWrapperTable->m_OperationResult_WaitFor = NULL;
	pWrapperTable->m_OperationResult_EnsureSuccess = NULL;
	pWrapperTable->m_OperationResult_InProgress = NULL;
	pWrapperTable->m_OperationResult_Success = NULL;
	pWrapperTable->m_OperationResult_GetErrorMessage = NULL;
	pWrapperTable->m_DataStream_GetUUID = NULL;
	pWrapperTable->m_DataStream_GetContext = NULL;
	pWrapperTable->m_DataStream_GetName = NULL;
	pWrapperTable->m_DataStream_GetMimeType = NULL;
	pWrapperTable->m_DataStream_GetSHA256 = NULL;
	pWrapperTable->m_DataStream_GetSize = NULL;
	pWrapperTable->m_DataStream_GetTimestamp = NULL;
	pWrapperTable->m_StreamUpload_GetName = NULL;
	pWrapperTable->m_StreamUpload_GetMimeType = NULL;
	pWrapperTable->m_StreamUpload_GetContextType = NULL;
	pWrapperTable->m_StreamUpload_UploadData = NULL;
	pWrapperTable->m_StreamUpload_UploadFile = NULL;
	pWrapperTable->m_StreamUpload_BeginChunking = NULL;
	pWrapperTable->m_StreamUpload_UploadChunk = NULL;
	pWrapperTable->m_StreamUpload_FinishChunking = NULL;
	pWrapperTable->m_StreamUpload_GetStatus = NULL;
	pWrapperTable->m_StreamUpload_GetDataStream = NULL;
	pWrapperTable->m_Connection_GetBaseURL = NULL;
	pWrapperTable->m_Connection_SetTimeouts = NULL;
	pWrapperTable->m_Connection_GetTimeout = NULL;
	pWrapperTable->m_Connection_GetRetryCount = NULL;
	pWrapperTable->m_Connection_AuthenticateWithPassword = NULL;
	pWrapperTable->m_Connection_IsAuthenticated = NULL;
	pWrapperTable->m_Connection_RefreshAuthentication = NULL;
	pWrapperTable->m_Connection_Ping = NULL;
	pWrapperTable->m_Connection_GetAuthToken = NULL;
	pWrapperTable->m_Connection_CreateUpload = NULL;
	pWrapperTable->m_Connection_PrepareBuild = NULL;
	pWrapperTable->m_GetVersion = NULL;
	pWrapperTable->m_GetLastError = NULL;
	pWrapperTable->m_ReleaseInstance = NULL;
	pWrapperTable->m_AcquireInstance = NULL;
	pWrapperTable->m_InjectComponent = NULL;
	pWrapperTable->m_GetSymbolLookupMethod = NULL;
	pWrapperTable->m_CreateConnection = NULL;
	
	return LIBAMCF_SUCCESS;
}

LibAMCFResult ReleaseLibAMCFWrapperTable(sLibAMCFDynamicWrapperTable * pWrapperTable)
{
	if (pWrapperTable == NULL)
		return LIBAMCF_ERROR_INVALIDPARAM;
	
	if (pWrapperTable->m_LibraryHandle != NULL) {
	#ifdef _WIN32
		HMODULE hModule = (HMODULE) pWrapperTable->m_LibraryHandle;
		FreeLibrary(hModule);
	#else // _WIN32
		dlclose(pWrapperTable->m_LibraryHandle);
	#endif // _WIN32
		return InitLibAMCFWrapperTable(pWrapperTable);
	}
	
	return LIBAMCF_SUCCESS;
}

LibAMCFResult LoadLibAMCFWrapperTable(sLibAMCFDynamicWrapperTable * pWrapperTable, const char * pLibraryFileName)
{
	if (pWrapperTable == NULL)
		return LIBAMCF_ERROR_INVALIDPARAM;
	if (pLibraryFileName == NULL)
		return LIBAMCF_ERROR_INVALIDPARAM;
	
	#ifdef _WIN32
	// Convert filename to UTF16-string
	int nLength = (int)strlen(pLibraryFileName);
	int nBufferSize = nLength * 2 + 2;
	wchar_t* wsLibraryFileName = (wchar_t*)malloc(nBufferSize*sizeof(wchar_t));
	memset(wsLibraryFileName, 0, nBufferSize*sizeof(wchar_t));
	int nResult = MultiByteToWideChar(CP_UTF8, 0, pLibraryFileName, nLength, wsLibraryFileName, nBufferSize);
	if (nResult == 0) {
		free(wsLibraryFileName);
		return LIBAMCF_ERROR_COULDNOTLOADLIBRARY;
	}
	
	HMODULE hLibrary = LoadLibraryW(wsLibraryFileName);
	free(wsLibraryFileName);
	if (hLibrary == 0) 
		return LIBAMCF_ERROR_COULDNOTLOADLIBRARY;
	#else // _WIN32
	void* hLibrary = dlopen(pLibraryFileName, RTLD_LAZY);
	if (hLibrary == 0) 
		return LIBAMCF_ERROR_COULDNOTLOADLIBRARY;
	dlerror();
	#endif // _WIN32
	
	#ifdef _WIN32
	pWrapperTable->m_OperationResult_WaitFor = (PLibAMCFOperationResult_WaitForPtr) GetProcAddress(hLibrary, "libamcf_operationresult_waitfor");
	#else // _WIN32
	pWrapperTable->m_OperationResult_WaitFor = (PLibAMCFOperationResult_WaitForPtr) dlsym(hLibrary, "libamcf_operationresult_waitfor");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_OperationResult_WaitFor == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_OperationResult_EnsureSuccess = (PLibAMCFOperationResult_EnsureSuccessPtr) GetProcAddress(hLibrary, "libamcf_operationresult_ensuresuccess");
	#else // _WIN32
	pWrapperTable->m_OperationResult_EnsureSuccess = (PLibAMCFOperationResult_EnsureSuccessPtr) dlsym(hLibrary, "libamcf_operationresult_ensuresuccess");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_OperationResult_EnsureSuccess == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_OperationResult_InProgress = (PLibAMCFOperationResult_InProgressPtr) GetProcAddress(hLibrary, "libamcf_operationresult_inprogress");
	#else // _WIN32
	pWrapperTable->m_OperationResult_InProgress = (PLibAMCFOperationResult_InProgressPtr) dlsym(hLibrary, "libamcf_operationresult_inprogress");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_OperationResult_InProgress == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_OperationResult_Success = (PLibAMCFOperationResult_SuccessPtr) GetProcAddress(hLibrary, "libamcf_operationresult_success");
	#else // _WIN32
	pWrapperTable->m_OperationResult_Success = (PLibAMCFOperationResult_SuccessPtr) dlsym(hLibrary, "libamcf_operationresult_success");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_OperationResult_Success == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_OperationResult_GetErrorMessage = (PLibAMCFOperationResult_GetErrorMessagePtr) GetProcAddress(hLibrary, "libamcf_operationresult_geterrormessage");
	#else // _WIN32
	pWrapperTable->m_OperationResult_GetErrorMessage = (PLibAMCFOperationResult_GetErrorMessagePtr) dlsym(hLibrary, "libamcf_operationresult_geterrormessage");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_OperationResult_GetErrorMessage == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_DataStream_GetUUID = (PLibAMCFDataStream_GetUUIDPtr) GetProcAddress(hLibrary, "libamcf_datastream_getuuid");
	#else // _WIN32
	pWrapperTable->m_DataStream_GetUUID = (PLibAMCFDataStream_GetUUIDPtr) dlsym(hLibrary, "libamcf_datastream_getuuid");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_DataStream_GetUUID == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_DataStream_GetContext = (PLibAMCFDataStream_GetContextPtr) GetProcAddress(hLibrary, "libamcf_datastream_getcontext");
	#else // _WIN32
	pWrapperTable->m_DataStream_GetContext = (PLibAMCFDataStream_GetContextPtr) dlsym(hLibrary, "libamcf_datastream_getcontext");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_DataStream_GetContext == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_DataStream_GetName = (PLibAMCFDataStream_GetNamePtr) GetProcAddress(hLibrary, "libamcf_datastream_getname");
	#else // _WIN32
	pWrapperTable->m_DataStream_GetName = (PLibAMCFDataStream_GetNamePtr) dlsym(hLibrary, "libamcf_datastream_getname");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_DataStream_GetName == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_DataStream_GetMimeType = (PLibAMCFDataStream_GetMimeTypePtr) GetProcAddress(hLibrary, "libamcf_datastream_getmimetype");
	#else // _WIN32
	pWrapperTable->m_DataStream_GetMimeType = (PLibAMCFDataStream_GetMimeTypePtr) dlsym(hLibrary, "libamcf_datastream_getmimetype");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_DataStream_GetMimeType == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_DataStream_GetSHA256 = (PLibAMCFDataStream_GetSHA256Ptr) GetProcAddress(hLibrary, "libamcf_datastream_getsha256");
	#else // _WIN32
	pWrapperTable->m_DataStream_GetSHA256 = (PLibAMCFDataStream_GetSHA256Ptr) dlsym(hLibrary, "libamcf_datastream_getsha256");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_DataStream_GetSHA256 == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_DataStream_GetSize = (PLibAMCFDataStream_GetSizePtr) GetProcAddress(hLibrary, "libamcf_datastream_getsize");
	#else // _WIN32
	pWrapperTable->m_DataStream_GetSize = (PLibAMCFDataStream_GetSizePtr) dlsym(hLibrary, "libamcf_datastream_getsize");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_DataStream_GetSize == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_DataStream_GetTimestamp = (PLibAMCFDataStream_GetTimestampPtr) GetProcAddress(hLibrary, "libamcf_datastream_gettimestamp");
	#else // _WIN32
	pWrapperTable->m_DataStream_GetTimestamp = (PLibAMCFDataStream_GetTimestampPtr) dlsym(hLibrary, "libamcf_datastream_gettimestamp");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_DataStream_GetTimestamp == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_GetName = (PLibAMCFStreamUpload_GetNamePtr) GetProcAddress(hLibrary, "libamcf_streamupload_getname");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_GetName = (PLibAMCFStreamUpload_GetNamePtr) dlsym(hLibrary, "libamcf_streamupload_getname");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_GetName == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_GetMimeType = (PLibAMCFStreamUpload_GetMimeTypePtr) GetProcAddress(hLibrary, "libamcf_streamupload_getmimetype");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_GetMimeType = (PLibAMCFStreamUpload_GetMimeTypePtr) dlsym(hLibrary, "libamcf_streamupload_getmimetype");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_GetMimeType == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_GetContextType = (PLibAMCFStreamUpload_GetContextTypePtr) GetProcAddress(hLibrary, "libamcf_streamupload_getcontexttype");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_GetContextType = (PLibAMCFStreamUpload_GetContextTypePtr) dlsym(hLibrary, "libamcf_streamupload_getcontexttype");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_GetContextType == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_UploadData = (PLibAMCFStreamUpload_UploadDataPtr) GetProcAddress(hLibrary, "libamcf_streamupload_uploaddata");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_UploadData = (PLibAMCFStreamUpload_UploadDataPtr) dlsym(hLibrary, "libamcf_streamupload_uploaddata");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_UploadData == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_UploadFile = (PLibAMCFStreamUpload_UploadFilePtr) GetProcAddress(hLibrary, "libamcf_streamupload_uploadfile");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_UploadFile = (PLibAMCFStreamUpload_UploadFilePtr) dlsym(hLibrary, "libamcf_streamupload_uploadfile");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_UploadFile == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_BeginChunking = (PLibAMCFStreamUpload_BeginChunkingPtr) GetProcAddress(hLibrary, "libamcf_streamupload_beginchunking");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_BeginChunking = (PLibAMCFStreamUpload_BeginChunkingPtr) dlsym(hLibrary, "libamcf_streamupload_beginchunking");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_BeginChunking == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_UploadChunk = (PLibAMCFStreamUpload_UploadChunkPtr) GetProcAddress(hLibrary, "libamcf_streamupload_uploadchunk");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_UploadChunk = (PLibAMCFStreamUpload_UploadChunkPtr) dlsym(hLibrary, "libamcf_streamupload_uploadchunk");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_UploadChunk == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_FinishChunking = (PLibAMCFStreamUpload_FinishChunkingPtr) GetProcAddress(hLibrary, "libamcf_streamupload_finishchunking");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_FinishChunking = (PLibAMCFStreamUpload_FinishChunkingPtr) dlsym(hLibrary, "libamcf_streamupload_finishchunking");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_FinishChunking == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_GetStatus = (PLibAMCFStreamUpload_GetStatusPtr) GetProcAddress(hLibrary, "libamcf_streamupload_getstatus");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_GetStatus = (PLibAMCFStreamUpload_GetStatusPtr) dlsym(hLibrary, "libamcf_streamupload_getstatus");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_GetStatus == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_StreamUpload_GetDataStream = (PLibAMCFStreamUpload_GetDataStreamPtr) GetProcAddress(hLibrary, "libamcf_streamupload_getdatastream");
	#else // _WIN32
	pWrapperTable->m_StreamUpload_GetDataStream = (PLibAMCFStreamUpload_GetDataStreamPtr) dlsym(hLibrary, "libamcf_streamupload_getdatastream");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_StreamUpload_GetDataStream == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_GetBaseURL = (PLibAMCFConnection_GetBaseURLPtr) GetProcAddress(hLibrary, "libamcf_connection_getbaseurl");
	#else // _WIN32
	pWrapperTable->m_Connection_GetBaseURL = (PLibAMCFConnection_GetBaseURLPtr) dlsym(hLibrary, "libamcf_connection_getbaseurl");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_GetBaseURL == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_SetTimeouts = (PLibAMCFConnection_SetTimeoutsPtr) GetProcAddress(hLibrary, "libamcf_connection_settimeouts");
	#else // _WIN32
	pWrapperTable->m_Connection_SetTimeouts = (PLibAMCFConnection_SetTimeoutsPtr) dlsym(hLibrary, "libamcf_connection_settimeouts");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_SetTimeouts == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_GetTimeout = (PLibAMCFConnection_GetTimeoutPtr) GetProcAddress(hLibrary, "libamcf_connection_gettimeout");
	#else // _WIN32
	pWrapperTable->m_Connection_GetTimeout = (PLibAMCFConnection_GetTimeoutPtr) dlsym(hLibrary, "libamcf_connection_gettimeout");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_GetTimeout == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_GetRetryCount = (PLibAMCFConnection_GetRetryCountPtr) GetProcAddress(hLibrary, "libamcf_connection_getretrycount");
	#else // _WIN32
	pWrapperTable->m_Connection_GetRetryCount = (PLibAMCFConnection_GetRetryCountPtr) dlsym(hLibrary, "libamcf_connection_getretrycount");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_GetRetryCount == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_AuthenticateWithPassword = (PLibAMCFConnection_AuthenticateWithPasswordPtr) GetProcAddress(hLibrary, "libamcf_connection_authenticatewithpassword");
	#else // _WIN32
	pWrapperTable->m_Connection_AuthenticateWithPassword = (PLibAMCFConnection_AuthenticateWithPasswordPtr) dlsym(hLibrary, "libamcf_connection_authenticatewithpassword");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_AuthenticateWithPassword == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_IsAuthenticated = (PLibAMCFConnection_IsAuthenticatedPtr) GetProcAddress(hLibrary, "libamcf_connection_isauthenticated");
	#else // _WIN32
	pWrapperTable->m_Connection_IsAuthenticated = (PLibAMCFConnection_IsAuthenticatedPtr) dlsym(hLibrary, "libamcf_connection_isauthenticated");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_IsAuthenticated == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_RefreshAuthentication = (PLibAMCFConnection_RefreshAuthenticationPtr) GetProcAddress(hLibrary, "libamcf_connection_refreshauthentication");
	#else // _WIN32
	pWrapperTable->m_Connection_RefreshAuthentication = (PLibAMCFConnection_RefreshAuthenticationPtr) dlsym(hLibrary, "libamcf_connection_refreshauthentication");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_RefreshAuthentication == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_Ping = (PLibAMCFConnection_PingPtr) GetProcAddress(hLibrary, "libamcf_connection_ping");
	#else // _WIN32
	pWrapperTable->m_Connection_Ping = (PLibAMCFConnection_PingPtr) dlsym(hLibrary, "libamcf_connection_ping");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_Ping == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_GetAuthToken = (PLibAMCFConnection_GetAuthTokenPtr) GetProcAddress(hLibrary, "libamcf_connection_getauthtoken");
	#else // _WIN32
	pWrapperTable->m_Connection_GetAuthToken = (PLibAMCFConnection_GetAuthTokenPtr) dlsym(hLibrary, "libamcf_connection_getauthtoken");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_GetAuthToken == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_CreateUpload = (PLibAMCFConnection_CreateUploadPtr) GetProcAddress(hLibrary, "libamcf_connection_createupload");
	#else // _WIN32
	pWrapperTable->m_Connection_CreateUpload = (PLibAMCFConnection_CreateUploadPtr) dlsym(hLibrary, "libamcf_connection_createupload");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_CreateUpload == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_Connection_PrepareBuild = (PLibAMCFConnection_PrepareBuildPtr) GetProcAddress(hLibrary, "libamcf_connection_preparebuild");
	#else // _WIN32
	pWrapperTable->m_Connection_PrepareBuild = (PLibAMCFConnection_PrepareBuildPtr) dlsym(hLibrary, "libamcf_connection_preparebuild");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_Connection_PrepareBuild == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_GetVersion = (PLibAMCFGetVersionPtr) GetProcAddress(hLibrary, "libamcf_getversion");
	#else // _WIN32
	pWrapperTable->m_GetVersion = (PLibAMCFGetVersionPtr) dlsym(hLibrary, "libamcf_getversion");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_GetVersion == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_GetLastError = (PLibAMCFGetLastErrorPtr) GetProcAddress(hLibrary, "libamcf_getlasterror");
	#else // _WIN32
	pWrapperTable->m_GetLastError = (PLibAMCFGetLastErrorPtr) dlsym(hLibrary, "libamcf_getlasterror");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_GetLastError == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_ReleaseInstance = (PLibAMCFReleaseInstancePtr) GetProcAddress(hLibrary, "libamcf_releaseinstance");
	#else // _WIN32
	pWrapperTable->m_ReleaseInstance = (PLibAMCFReleaseInstancePtr) dlsym(hLibrary, "libamcf_releaseinstance");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_ReleaseInstance == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_AcquireInstance = (PLibAMCFAcquireInstancePtr) GetProcAddress(hLibrary, "libamcf_acquireinstance");
	#else // _WIN32
	pWrapperTable->m_AcquireInstance = (PLibAMCFAcquireInstancePtr) dlsym(hLibrary, "libamcf_acquireinstance");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_AcquireInstance == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_InjectComponent = (PLibAMCFInjectComponentPtr) GetProcAddress(hLibrary, "libamcf_injectcomponent");
	#else // _WIN32
	pWrapperTable->m_InjectComponent = (PLibAMCFInjectComponentPtr) dlsym(hLibrary, "libamcf_injectcomponent");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_InjectComponent == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_GetSymbolLookupMethod = (PLibAMCFGetSymbolLookupMethodPtr) GetProcAddress(hLibrary, "libamcf_getsymbollookupmethod");
	#else // _WIN32
	pWrapperTable->m_GetSymbolLookupMethod = (PLibAMCFGetSymbolLookupMethodPtr) dlsym(hLibrary, "libamcf_getsymbollookupmethod");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_GetSymbolLookupMethod == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	#ifdef _WIN32
	pWrapperTable->m_CreateConnection = (PLibAMCFCreateConnectionPtr) GetProcAddress(hLibrary, "libamcf_createconnection");
	#else // _WIN32
	pWrapperTable->m_CreateConnection = (PLibAMCFCreateConnectionPtr) dlsym(hLibrary, "libamcf_createconnection");
	dlerror();
	#endif // _WIN32
	if (pWrapperTable->m_CreateConnection == NULL)
		return LIBAMCF_ERROR_COULDNOTFINDLIBRARYEXPORT;
	
	pWrapperTable->m_LibraryHandle = hLibrary;
	return LIBAMCF_SUCCESS;
}

