/*++

Copyright (C) 2020 Autodesk Inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Autodesk Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL AUTODESK INC. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


This file has been generated by the Automatic Component Toolkit (ACT) version 1.8.0-develop.

Abstract: This is an autogenerated C++-Header file in order to allow an easy
 use of MC Driver Euler

Interface version: 2.0.0

*/

#ifndef __LIBMCDRIVER_EULER_CPPHEADER_DYNAMIC_CPP
#define __LIBMCDRIVER_EULER_CPPHEADER_DYNAMIC_CPP

#include "libmcdriver_euler_types.hpp"
#include "libmcdriver_euler_dynamic.h"

#include "libmcenv_dynamic.hpp"

#ifdef _WIN32
#include <windows.h>
#else // _WIN32
#include <dlfcn.h>
#endif // _WIN32
#include <string>
#include <memory>
#include <vector>
#include <exception>

namespace LibMCDriver_Euler {

/*************************************************************************************************************************
 Forward Declaration of all classes
**************************************************************************************************************************/
class CWrapper;
class CBase;
class CDriver;
class CEulerConnection;
class CDriver_Euler;

/*************************************************************************************************************************
 Declaration of deprecated class types
**************************************************************************************************************************/
typedef CWrapper CLibMCDriver_EulerWrapper;
typedef CBase CLibMCDriver_EulerBase;
typedef CDriver CLibMCDriver_EulerDriver;
typedef CEulerConnection CLibMCDriver_EulerEulerConnection;
typedef CDriver_Euler CLibMCDriver_EulerDriver_Euler;

/*************************************************************************************************************************
 Declaration of shared pointer types
**************************************************************************************************************************/
typedef std::shared_ptr<CWrapper> PWrapper;
typedef std::shared_ptr<CBase> PBase;
typedef std::shared_ptr<CDriver> PDriver;
typedef std::shared_ptr<CEulerConnection> PEulerConnection;
typedef std::shared_ptr<CDriver_Euler> PDriver_Euler;

/*************************************************************************************************************************
 Declaration of deprecated shared pointer types
**************************************************************************************************************************/
typedef PWrapper PLibMCDriver_EulerWrapper;
typedef PBase PLibMCDriver_EulerBase;
typedef PDriver PLibMCDriver_EulerDriver;
typedef PEulerConnection PLibMCDriver_EulerEulerConnection;
typedef PDriver_Euler PLibMCDriver_EulerDriver_Euler;


/*************************************************************************************************************************
 classParam Definition
**************************************************************************************************************************/

template<class T> class classParam {
private:
	const T* m_ptr;

public:
	classParam(const T* ptr)
		: m_ptr (ptr)
	{
	}

	classParam(std::shared_ptr <T> sharedPtr)
		: m_ptr (sharedPtr.get())
	{
	}

	LibMCDriver_EulerHandle GetHandle()
	{
		if (m_ptr != nullptr)
			return m_ptr->handle();
		return nullptr;
	}
};

/*************************************************************************************************************************
 Class ELibMCDriver_EulerException 
**************************************************************************************************************************/
class ELibMCDriver_EulerException : public std::exception {
protected:
	/**
	* Error code for the Exception.
	*/
	LibMCDriver_EulerResult m_errorCode;
	/**
	* Error message for the Exception.
	*/
	std::string m_errorMessage;
	std::string m_originalErrorMessage;

public:
	/**
	* Exception Constructor.
	*/
	ELibMCDriver_EulerException(LibMCDriver_EulerResult errorCode, const std::string & sErrorMessage)
		: m_errorCode(errorCode), m_originalErrorMessage(sErrorMessage)
	{
		m_errorMessage = buildErrorMessage();
	}

	/**
	* Returns error code
	*/
	LibMCDriver_EulerResult getErrorCode() const noexcept
	{
		return m_errorCode;
	}

	/**
	* Returns error message
	*/
	const char* what() const noexcept
	{
		return m_errorMessage.c_str();
	}

	const char* getErrorMessage() const noexcept
	{
		return m_originalErrorMessage.c_str();
	}

	const char* getErrorName() const noexcept
	{
		switch(getErrorCode()) {
			case LIBMCDRIVER_EULER_SUCCESS: return "SUCCESS";
			case LIBMCDRIVER_EULER_ERROR_NOTIMPLEMENTED: return "NOTIMPLEMENTED";
			case LIBMCDRIVER_EULER_ERROR_INVALIDPARAM: return "INVALIDPARAM";
			case LIBMCDRIVER_EULER_ERROR_INVALIDCAST: return "INVALIDCAST";
			case LIBMCDRIVER_EULER_ERROR_BUFFERTOOSMALL: return "BUFFERTOOSMALL";
			case LIBMCDRIVER_EULER_ERROR_GENERICEXCEPTION: return "GENERICEXCEPTION";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTLOADLIBRARY: return "COULDNOTLOADLIBRARY";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT: return "COULDNOTFINDLIBRARYEXPORT";
			case LIBMCDRIVER_EULER_ERROR_INCOMPATIBLEBINARYVERSION: return "INCOMPATIBLEBINARYVERSION";
			case LIBMCDRIVER_EULER_ERROR_DRIVERERROR: return "DRIVERERROR";
			case LIBMCDRIVER_EULER_ERROR_DRIVERNOTINITIALISED: return "DRIVERNOTINITIALISED";
			case LIBMCDRIVER_EULER_ERROR_DRIVERNOTCONNECTED: return "DRIVERNOTCONNECTED";
			case LIBMCDRIVER_EULER_ERROR_INVALIDDRIVERPROTOCOL: return "INVALIDDRIVERPROTOCOL";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTPARSEDRIVERPROTOCOL: return "COULDNOTPARSEDRIVERPROTOCOL";
			case LIBMCDRIVER_EULER_ERROR_NOTCONNECTED: return "NOTCONNECTED";
			case LIBMCDRIVER_EULER_ERROR_INTEGERVALUEOUTOFRANGE: return "INTEGERVALUEOUTOFRANGE";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTREADDATA: return "COULDNOTREADDATA";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTREADHANDLEVALUE: return "COULDNOTREADHANDLEVALUE";
			case LIBMCDRIVER_EULER_ERROR_NAMELENGTHEXCEEDSMAXIMUM: return "NAMELENGTHEXCEEDSMAXIMUM";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTCONNECT: return "COULDNOTCONNECT";
			case LIBMCDRIVER_EULER_ERROR_HASBEENDISCONNECTED: return "HASBEENDISCONNECTED";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTSTARTHEARTBEAT: return "COULDNOTSTARTHEARTBEAT";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTSTOPHEARTBEAT: return "COULDNOTSTOPHEARTBEAT";
			case LIBMCDRIVER_EULER_ERROR_EMPTYJOBNAME: return "EMPTYJOBNAME";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTCREATEBUILD: return "COULDNOTCREATEBUILD";
			case LIBMCDRIVER_EULER_ERROR_INVALIDIDENTIFIER: return "INVALIDIDENTIFIER";
			case LIBMCDRIVER_EULER_ERROR_CONNECTIONIDENTIFIERALREADYINUSE: return "CONNECTIONIDENTIFIERALREADYINUSE";
			case LIBMCDRIVER_EULER_ERROR_CONNECTIONIDENTIFIERNOTFOUND: return "CONNECTIONIDENTIFIERNOTFOUND";
			case LIBMCDRIVER_EULER_ERROR_LIBEULERDLLNOTSPECIFIED: return "LIBEULERDLLNOTSPECIFIED";
			case LIBMCDRIVER_EULER_ERROR_INVALIDBUILDJOBID: return "INVALIDBUILDJOBID";
			case LIBMCDRIVER_EULER_ERROR_INVALIDIMAGETYPE: return "INVALIDIMAGETYPE";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTUPLOADLAYERIMAGE: return "COULDNOTUPLOADLAYERIMAGE";
			case LIBMCDRIVER_EULER_ERROR_INVALIDJOBSTATUS: return "INVALIDJOBSTATUS";
			case LIBMCDRIVER_EULER_ERROR_COULDUPDATEJOBSTATUS: return "COULDUPDATEJOBSTATUS";
			case LIBMCDRIVER_EULER_ERROR_INVALIDLICENSERESOURCE: return "INVALIDLICENSERESOURCE";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTENCODEJPEGIMAGE: return "COULDNOTENCODEJPEGIMAGE";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTREADLICENSEDATA: return "COULDNOTREADLICENSEDATA";
			case LIBMCDRIVER_EULER_ERROR_INVALIDLICENSEDATA: return "INVALIDLICENSEDATA";
		}
		return "UNKNOWN";
	}

	const char* getErrorDescription() const noexcept
	{
		switch(getErrorCode()) {
			case LIBMCDRIVER_EULER_SUCCESS: return "success";
			case LIBMCDRIVER_EULER_ERROR_NOTIMPLEMENTED: return "functionality not implemented";
			case LIBMCDRIVER_EULER_ERROR_INVALIDPARAM: return "an invalid parameter was passed";
			case LIBMCDRIVER_EULER_ERROR_INVALIDCAST: return "a type cast failed";
			case LIBMCDRIVER_EULER_ERROR_BUFFERTOOSMALL: return "a provided buffer is too small";
			case LIBMCDRIVER_EULER_ERROR_GENERICEXCEPTION: return "a generic exception occurred";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTLOADLIBRARY: return "the library could not be loaded";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT: return "a required exported symbol could not be found in the library";
			case LIBMCDRIVER_EULER_ERROR_INCOMPATIBLEBINARYVERSION: return "the version of the binary interface does not match the bindings interface";
			case LIBMCDRIVER_EULER_ERROR_DRIVERERROR: return "a driver error occured";
			case LIBMCDRIVER_EULER_ERROR_DRIVERNOTINITIALISED: return "the driver is not initialised";
			case LIBMCDRIVER_EULER_ERROR_DRIVERNOTCONNECTED: return "the driver is not connected";
			case LIBMCDRIVER_EULER_ERROR_INVALIDDRIVERPROTOCOL: return "invalid driver protocol definition";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTPARSEDRIVERPROTOCOL: return "could not parse driver protocol";
			case LIBMCDRIVER_EULER_ERROR_NOTCONNECTED: return "Not connected";
			case LIBMCDRIVER_EULER_ERROR_INTEGERVALUEOUTOFRANGE: return "Integer value out of range";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTREADDATA: return "Could not read data";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTREADHANDLEVALUE: return "Could not read handle value";
			case LIBMCDRIVER_EULER_ERROR_NAMELENGTHEXCEEDSMAXIMUM: return "Name length exceeds maximum";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTCONNECT: return "Could not connect";
			case LIBMCDRIVER_EULER_ERROR_HASBEENDISCONNECTED: return "Has been disconnected";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTSTARTHEARTBEAT: return "Could not start heartbeat";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTSTOPHEARTBEAT: return "Could not stop heartbeat";
			case LIBMCDRIVER_EULER_ERROR_EMPTYJOBNAME: return "Empty job name";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTCREATEBUILD: return "Could not create build";
			case LIBMCDRIVER_EULER_ERROR_INVALIDIDENTIFIER: return "Invalid identifier";
			case LIBMCDRIVER_EULER_ERROR_CONNECTIONIDENTIFIERALREADYINUSE: return "Connection identifier already in use";
			case LIBMCDRIVER_EULER_ERROR_CONNECTIONIDENTIFIERNOTFOUND: return "Connection identifier not found";
			case LIBMCDRIVER_EULER_ERROR_LIBEULERDLLNOTSPECIFIED: return "LibEuler dll not specified";
			case LIBMCDRIVER_EULER_ERROR_INVALIDBUILDJOBID: return "Invalid build job id";
			case LIBMCDRIVER_EULER_ERROR_INVALIDIMAGETYPE: return "Invalid image type";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTUPLOADLAYERIMAGE: return "Could not upload layer image";
			case LIBMCDRIVER_EULER_ERROR_INVALIDJOBSTATUS: return "Invalid job status";
			case LIBMCDRIVER_EULER_ERROR_COULDUPDATEJOBSTATUS: return "Could not update job status";
			case LIBMCDRIVER_EULER_ERROR_INVALIDLICENSERESOURCE: return "Invalid license resource";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTENCODEJPEGIMAGE: return "Could not encode JPEG Image";
			case LIBMCDRIVER_EULER_ERROR_COULDNOTREADLICENSEDATA: return "Could not read license data";
			case LIBMCDRIVER_EULER_ERROR_INVALIDLICENSEDATA: return "Invalid license data";
		}
		return "unknown error";
	}

private:

	std::string buildErrorMessage() const noexcept
	{
		std::string msg = m_originalErrorMessage;
		if (msg.empty()) {
			msg = getErrorDescription();
		}
		return std::string("Error: ") + getErrorName() + ": " + msg;
	}
};

/*************************************************************************************************************************
 Class CInputVector
**************************************************************************************************************************/
template <typename T>
class CInputVector {
private:
	
	const T* m_data;
	size_t m_size;
	
public:
	
	CInputVector(const std::vector<T>& vec)
		: m_data( vec.data() ), m_size( vec.size() )
	{
	}
	
	CInputVector(const T* in_data, size_t in_size)
		: m_data( in_data ), m_size(in_size )
	{
	}
	
	const T* data() const
	{
		return m_data;
	}
	
	size_t size() const
	{
		return m_size;
	}
	
};

// declare deprecated class name
template<typename T>
using CLibMCDriver_EulerInputVector = CInputVector<T>;

/*************************************************************************************************************************
 Class CWrapper 
**************************************************************************************************************************/
class CWrapper {
public:
	
	explicit CWrapper(void* pSymbolLookupMethod)
	{
		CheckError(nullptr, initWrapperTable(&m_WrapperTable));
		CheckError(nullptr, loadWrapperTableFromSymbolLookupMethod(&m_WrapperTable, pSymbolLookupMethod));
		
		CheckError(nullptr, checkBinaryVersion());
	}
	
	explicit CWrapper(const std::string &sFileName)
	{
		CheckError(nullptr, initWrapperTable(&m_WrapperTable));
		CheckError(nullptr, loadWrapperTable(&m_WrapperTable, sFileName.c_str()));
		
		CheckError(nullptr, checkBinaryVersion());
	}
	
	static PWrapper loadLibrary(const std::string &sFileName)
	{
		return std::make_shared<CWrapper>(sFileName);
	}
	
	static PWrapper loadLibraryFromSymbolLookupMethod(void* pSymbolLookupMethod)
	{
		return std::make_shared<CWrapper>(pSymbolLookupMethod);
	}
	
	~CWrapper()
	{
		releaseWrapperTable(&m_WrapperTable);
	}
	
	inline void CheckError(CBase * pBaseClass, LibMCDriver_EulerResult nResult);

	inline void GetVersion(LibMCDriver_Euler_uint32 & nMajor, LibMCDriver_Euler_uint32 & nMinor, LibMCDriver_Euler_uint32 & nMicro);
	inline bool GetLastError(classParam<CBase> pInstance, std::string & sErrorMessage);
	inline void ReleaseInstance(classParam<CBase> pInstance);
	inline void AcquireInstance(classParam<CBase> pInstance);
	inline void InjectComponent(const std::string & sNameSpace, const LibMCDriver_Euler_pvoid pSymbolAddressMethod);
	inline LibMCDriver_Euler_pvoid GetSymbolLookupMethod();
	inline PDriver CreateDriver(const std::string & sName, const std::string & sType, classParam<LibMCEnv::CDriverEnvironment> pDriverEnvironment);

private:
	sLibMCDriver_EulerDynamicWrapperTable m_WrapperTable;
	// Injected Components
	LibMCEnv::PWrapper m_pLibMCEnvWrapper;

	
	LibMCDriver_EulerResult checkBinaryVersion()
	{
		LibMCDriver_Euler_uint32 nMajor, nMinor, nMicro;
		GetVersion(nMajor, nMinor, nMicro);
		if (nMajor != LIBMCDRIVER_EULER_VERSION_MAJOR) {
			return LIBMCDRIVER_EULER_ERROR_INCOMPATIBLEBINARYVERSION;
		}
		return LIBMCDRIVER_EULER_SUCCESS;
	}
	LibMCDriver_EulerResult initWrapperTable(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable);
	LibMCDriver_EulerResult releaseWrapperTable(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable);
	LibMCDriver_EulerResult loadWrapperTable(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable, const char * pLibraryFileName);
	LibMCDriver_EulerResult loadWrapperTableFromSymbolLookupMethod(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable, void* pSymbolLookupMethod);

	friend class CBase;
	friend class CDriver;
	friend class CEulerConnection;
	friend class CDriver_Euler;

};

	
/*************************************************************************************************************************
 Class CBase 
**************************************************************************************************************************/
class CBase {
public:
	
protected:
	/* Wrapper Object that created the class. */
	CWrapper * m_pWrapper;
	/* Handle to Instance in library*/
	LibMCDriver_EulerHandle m_pHandle;

	/* Checks for an Error code and raises Exceptions */
	void CheckError(LibMCDriver_EulerResult nResult)
	{
		if (m_pWrapper != nullptr)
			m_pWrapper->CheckError(this, nResult);
	}
public:
	/**
	* CBase::CBase - Constructor for Base class.
	*/
	CBase(CWrapper * pWrapper, LibMCDriver_EulerHandle pHandle)
		: m_pWrapper(pWrapper), m_pHandle(pHandle)
	{
	}

	/**
	* CBase::~CBase - Destructor for Base class.
	*/
	virtual ~CBase()
	{
		if (m_pWrapper != nullptr)
			m_pWrapper->ReleaseInstance(this);
		m_pWrapper = nullptr;
	}

	/**
	* CBase::handle - Returns handle to instance.
	*/
	LibMCDriver_EulerHandle handle() const
	{
		return m_pHandle;
	}

	/**
	* CBase::wrapper - Returns wrapper instance.
	*/
	CWrapper * wrapper() const
	{
		return m_pWrapper;
	}
	
	friend class CWrapper;
};
	
/*************************************************************************************************************************
 Class CDriver 
**************************************************************************************************************************/
class CDriver : public CBase {
public:
	
	/**
	* CDriver::CDriver - Constructor for Driver class.
	*/
	CDriver(CWrapper* pWrapper, LibMCDriver_EulerHandle pHandle)
		: CBase(pWrapper, pHandle)
	{
	}
	
	inline void Configure(const std::string & sConfigurationString);
	inline std::string GetName();
	inline std::string GetType();
	inline void GetVersion(LibMCDriver_Euler_uint32 & nMajor, LibMCDriver_Euler_uint32 & nMinor, LibMCDriver_Euler_uint32 & nMicro, std::string & sBuild);
	inline void QueryParameters();
	inline void QueryParametersEx(classParam<LibMCEnv::CDriverStatusUpdateSession> pDriverUpdateInstance);
};
	
/*************************************************************************************************************************
 Class CEulerConnection 
**************************************************************************************************************************/
class CEulerConnection : public CBase {
public:
	
	/**
	* CEulerConnection::CEulerConnection - Constructor for EulerConnection class.
	*/
	CEulerConnection(CWrapper* pWrapper, LibMCDriver_EulerHandle pHandle)
		: CBase(pWrapper, pHandle)
	{
	}
	
	inline void Disconnect();
	inline std::string GetIdentifier();
	inline std::string GetApplicationName();
	inline std::string GetApplicationVersion();
	inline std::string GetBaseURL();
	inline std::string GetAPIKey();
	inline std::string GetDeviceID();
	inline void StartHeartBeat();
	inline void StopHeartBeat();
	inline std::string CreateBuild(const std::string & sJobName, const LibMCDriver_Euler_uint32 nLayerCount);
	inline void UploadImage(const std::string & sBuildJobID, const LibMCDriver_Euler_uint32 nLayerIndex, const eEulerImageType eImageType, classParam<LibMCEnv::CImageData> pImage);
	inline void SetJobStatus(const std::string & sBuildJobID, const eEulerJobStatus eJobStatus);
};
	
/*************************************************************************************************************************
 Class CDriver_Euler 
**************************************************************************************************************************/
class CDriver_Euler : public CDriver {
public:
	
	/**
	* CDriver_Euler::CDriver_Euler - Constructor for Driver_Euler class.
	*/
	CDriver_Euler(CWrapper* pWrapper, LibMCDriver_EulerHandle pHandle)
		: CDriver(pWrapper, pHandle)
	{
	}
	
	inline void SetCustomSDKResource(const std::string & sResourceName);
	inline void SetApplicationDetails(const std::string & sApplicationName, const std::string & sApplicationVersion);
	inline PEulerConnection Connect(const std::string & sIdentifier, const std::string & sBaseURL, const std::string & sAPIKey, const std::string & sDeviceID);
	inline PEulerConnection ConnectWithLicenseData(const std::string & sIdentifier, const CInputVector<LibMCDriver_Euler_uint8> & LicenseDataBuffer, const std::string & sDeviceID);
	inline PEulerConnection ConnectWithLicenseResource(const std::string & sIdentifier, const std::string & sLicenseResourceName, const std::string & sDeviceID);
	inline PEulerConnection FindConnection(const std::string & sIdentifier);
	inline bool ConnectionExists(const std::string & sIdentifier);
	inline void CloseAllConnections();
};
	
	/**
	* CWrapper::GetVersion - retrieves the binary version of this library.
	* @param[out] nMajor - returns the major version of this library
	* @param[out] nMinor - returns the minor version of this library
	* @param[out] nMicro - returns the micro version of this library
	*/
	inline void CWrapper::GetVersion(LibMCDriver_Euler_uint32 & nMajor, LibMCDriver_Euler_uint32 & nMinor, LibMCDriver_Euler_uint32 & nMicro)
	{
		CheckError(nullptr,m_WrapperTable.m_GetVersion(&nMajor, &nMinor, &nMicro));
	}
	
	/**
	* CWrapper::GetLastError - Returns the last error recorded on this object
	* @param[in] pInstance - Instance Handle
	* @param[out] sErrorMessage - Message of the last error
	* @return Is there a last error to query
	*/
	inline bool CWrapper::GetLastError(classParam<CBase> pInstance, std::string & sErrorMessage)
	{
		LibMCDriver_EulerHandle hInstance = pInstance.GetHandle();
		LibMCDriver_Euler_uint32 bytesNeededErrorMessage = 0;
		LibMCDriver_Euler_uint32 bytesWrittenErrorMessage = 0;
		bool resultHasError = 0;
		CheckError(nullptr,m_WrapperTable.m_GetLastError(hInstance, 0, &bytesNeededErrorMessage, nullptr, &resultHasError));
		std::vector<char> bufferErrorMessage(bytesNeededErrorMessage);
		CheckError(nullptr,m_WrapperTable.m_GetLastError(hInstance, bytesNeededErrorMessage, &bytesWrittenErrorMessage, &bufferErrorMessage[0], &resultHasError));
		sErrorMessage = std::string(&bufferErrorMessage[0]);
		
		return resultHasError;
	}
	
	/**
	* CWrapper::ReleaseInstance - Releases shared ownership of an Instance
	* @param[in] pInstance - Instance Handle
	*/
	inline void CWrapper::ReleaseInstance(classParam<CBase> pInstance)
	{
		LibMCDriver_EulerHandle hInstance = pInstance.GetHandle();
		CheckError(nullptr,m_WrapperTable.m_ReleaseInstance(hInstance));
	}
	
	/**
	* CWrapper::AcquireInstance - Acquires shared ownership of an Instance
	* @param[in] pInstance - Instance Handle
	*/
	inline void CWrapper::AcquireInstance(classParam<CBase> pInstance)
	{
		LibMCDriver_EulerHandle hInstance = pInstance.GetHandle();
		CheckError(nullptr,m_WrapperTable.m_AcquireInstance(hInstance));
	}
	
	/**
	* CWrapper::InjectComponent - Injects an imported component for usage within this component
	* @param[in] sNameSpace - NameSpace of the injected component
	* @param[in] pSymbolAddressMethod - Address of the SymbolAddressMethod of the injected component
	*/
	inline void CWrapper::InjectComponent(const std::string & sNameSpace, const LibMCDriver_Euler_pvoid pSymbolAddressMethod)
	{
		CheckError(nullptr,m_WrapperTable.m_InjectComponent(sNameSpace.c_str(), pSymbolAddressMethod));
		
		bool bNameSpaceFound = false;
		if (sNameSpace == "LibMCEnv") {
			if (m_pLibMCEnvWrapper != nullptr) {
				throw ELibMCDriver_EulerException(LIBMCDRIVER_EULER_ERROR_COULDNOTLOADLIBRARY, "Library with namespace " + sNameSpace + " is already registered.");
			}
			m_pLibMCEnvWrapper = LibMCEnv::CWrapper::loadLibraryFromSymbolLookupMethod(pSymbolAddressMethod);
			bNameSpaceFound = true;
		}
		if (!bNameSpaceFound)
			throw ELibMCDriver_EulerException(LIBMCDRIVER_EULER_ERROR_COULDNOTLOADLIBRARY, "Unknown namespace " + sNameSpace);
	}
	
	/**
	* CWrapper::GetSymbolLookupMethod - Returns the address of the SymbolLookupMethod
	* @return Address of the SymbolAddressMethod
	*/
	inline LibMCDriver_Euler_pvoid CWrapper::GetSymbolLookupMethod()
	{
		LibMCDriver_Euler_pvoid resultSymbolLookupMethod = 0;
		CheckError(nullptr,m_WrapperTable.m_GetSymbolLookupMethod(&resultSymbolLookupMethod));
		
		return resultSymbolLookupMethod;
	}
	
	/**
	* CWrapper::CreateDriver - Creates a driver instance with a specific name.
	* @param[in] sName - Name of driver to be created.
	* @param[in] sType - Type of driver to be created.
	* @param[in] pDriverEnvironment - Environment of this driver.
	* @return New Driver instance
	*/
	inline PDriver CWrapper::CreateDriver(const std::string & sName, const std::string & sType, classParam<LibMCEnv::CDriverEnvironment> pDriverEnvironment)
	{
		LibMCEnvHandle hDriverEnvironment = pDriverEnvironment.GetHandle();
		LibMCDriver_EulerHandle hInstance = nullptr;
		CheckError(nullptr,m_WrapperTable.m_CreateDriver(sName.c_str(), sType.c_str(), hDriverEnvironment, &hInstance));
		
		if (hInstance) {
			return std::make_shared<CDriver>(this, hInstance);
		} else {
			return nullptr;
		}
	}
	
	inline void CWrapper::CheckError(CBase * pBaseClass, LibMCDriver_EulerResult nResult)
	{
		if (nResult != 0) {
			std::string sErrorMessage;
			if (pBaseClass != nullptr) {
				GetLastError(pBaseClass, sErrorMessage);
			}
			throw ELibMCDriver_EulerException(nResult, sErrorMessage);
		}
	}
	

	inline LibMCDriver_EulerResult CWrapper::initWrapperTable(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable)
	{
		if (pWrapperTable == nullptr)
			return LIBMCDRIVER_EULER_ERROR_INVALIDPARAM;
		
		pWrapperTable->m_LibraryHandle = nullptr;
		pWrapperTable->m_Driver_Configure = nullptr;
		pWrapperTable->m_Driver_GetName = nullptr;
		pWrapperTable->m_Driver_GetType = nullptr;
		pWrapperTable->m_Driver_GetVersion = nullptr;
		pWrapperTable->m_Driver_QueryParameters = nullptr;
		pWrapperTable->m_Driver_QueryParametersEx = nullptr;
		pWrapperTable->m_EulerConnection_Disconnect = nullptr;
		pWrapperTable->m_EulerConnection_GetIdentifier = nullptr;
		pWrapperTable->m_EulerConnection_GetApplicationName = nullptr;
		pWrapperTable->m_EulerConnection_GetApplicationVersion = nullptr;
		pWrapperTable->m_EulerConnection_GetBaseURL = nullptr;
		pWrapperTable->m_EulerConnection_GetAPIKey = nullptr;
		pWrapperTable->m_EulerConnection_GetDeviceID = nullptr;
		pWrapperTable->m_EulerConnection_StartHeartBeat = nullptr;
		pWrapperTable->m_EulerConnection_StopHeartBeat = nullptr;
		pWrapperTable->m_EulerConnection_CreateBuild = nullptr;
		pWrapperTable->m_EulerConnection_UploadImage = nullptr;
		pWrapperTable->m_EulerConnection_SetJobStatus = nullptr;
		pWrapperTable->m_Driver_Euler_SetCustomSDKResource = nullptr;
		pWrapperTable->m_Driver_Euler_SetApplicationDetails = nullptr;
		pWrapperTable->m_Driver_Euler_Connect = nullptr;
		pWrapperTable->m_Driver_Euler_ConnectWithLicenseData = nullptr;
		pWrapperTable->m_Driver_Euler_ConnectWithLicenseResource = nullptr;
		pWrapperTable->m_Driver_Euler_FindConnection = nullptr;
		pWrapperTable->m_Driver_Euler_ConnectionExists = nullptr;
		pWrapperTable->m_Driver_Euler_CloseAllConnections = nullptr;
		pWrapperTable->m_GetVersion = nullptr;
		pWrapperTable->m_GetLastError = nullptr;
		pWrapperTable->m_ReleaseInstance = nullptr;
		pWrapperTable->m_AcquireInstance = nullptr;
		pWrapperTable->m_InjectComponent = nullptr;
		pWrapperTable->m_GetSymbolLookupMethod = nullptr;
		pWrapperTable->m_CreateDriver = nullptr;
		
		return LIBMCDRIVER_EULER_SUCCESS;
	}

	inline LibMCDriver_EulerResult CWrapper::releaseWrapperTable(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable)
	{
		if (pWrapperTable == nullptr)
			return LIBMCDRIVER_EULER_ERROR_INVALIDPARAM;
		
		if (pWrapperTable->m_LibraryHandle != nullptr) {
		#ifdef _WIN32
			HMODULE hModule = (HMODULE) pWrapperTable->m_LibraryHandle;
			FreeLibrary(hModule);
		#else // _WIN32
			dlclose(pWrapperTable->m_LibraryHandle);
		#endif // _WIN32
			return initWrapperTable(pWrapperTable);
		}
		
		return LIBMCDRIVER_EULER_SUCCESS;
	}

	inline LibMCDriver_EulerResult CWrapper::loadWrapperTable(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable, const char * pLibraryFileName)
	{
		if (pWrapperTable == nullptr)
			return LIBMCDRIVER_EULER_ERROR_INVALIDPARAM;
		if (pLibraryFileName == nullptr)
			return LIBMCDRIVER_EULER_ERROR_INVALIDPARAM;
		
		#ifdef _WIN32
		// Convert filename to UTF16-string
		int nLength = 0;
		while ((pLibraryFileName[nLength] != 0) && (nLength < MAX_PATH))
			nLength++;
		int nBufferSize = nLength * 2 + 2;
		std::vector<wchar_t> wsLibraryFileName(nBufferSize);
		int nResult = MultiByteToWideChar(CP_UTF8, 0, pLibraryFileName, nLength, &wsLibraryFileName[0], nBufferSize);
		if (nResult == 0)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTLOADLIBRARY;
		
		HMODULE hLibrary = LoadLibraryW(wsLibraryFileName.data());
		if (hLibrary == 0) 
			return LIBMCDRIVER_EULER_ERROR_COULDNOTLOADLIBRARY;
		#else // _WIN32
		void* hLibrary = dlopen(pLibraryFileName, RTLD_LAZY);
		if (hLibrary == 0) 
			return LIBMCDRIVER_EULER_ERROR_COULDNOTLOADLIBRARY;
		dlerror();
		#endif // _WIN32
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Configure = (PLibMCDriver_EulerDriver_ConfigurePtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_configure");
		#else // _WIN32
		pWrapperTable->m_Driver_Configure = (PLibMCDriver_EulerDriver_ConfigurePtr) dlsym(hLibrary, "libmcdriver_euler_driver_configure");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Configure == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_GetName = (PLibMCDriver_EulerDriver_GetNamePtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_getname");
		#else // _WIN32
		pWrapperTable->m_Driver_GetName = (PLibMCDriver_EulerDriver_GetNamePtr) dlsym(hLibrary, "libmcdriver_euler_driver_getname");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_GetName == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_GetType = (PLibMCDriver_EulerDriver_GetTypePtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_gettype");
		#else // _WIN32
		pWrapperTable->m_Driver_GetType = (PLibMCDriver_EulerDriver_GetTypePtr) dlsym(hLibrary, "libmcdriver_euler_driver_gettype");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_GetType == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_GetVersion = (PLibMCDriver_EulerDriver_GetVersionPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_getversion");
		#else // _WIN32
		pWrapperTable->m_Driver_GetVersion = (PLibMCDriver_EulerDriver_GetVersionPtr) dlsym(hLibrary, "libmcdriver_euler_driver_getversion");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_GetVersion == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_QueryParameters = (PLibMCDriver_EulerDriver_QueryParametersPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_queryparameters");
		#else // _WIN32
		pWrapperTable->m_Driver_QueryParameters = (PLibMCDriver_EulerDriver_QueryParametersPtr) dlsym(hLibrary, "libmcdriver_euler_driver_queryparameters");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_QueryParameters == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_QueryParametersEx = (PLibMCDriver_EulerDriver_QueryParametersExPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_queryparametersex");
		#else // _WIN32
		pWrapperTable->m_Driver_QueryParametersEx = (PLibMCDriver_EulerDriver_QueryParametersExPtr) dlsym(hLibrary, "libmcdriver_euler_driver_queryparametersex");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_QueryParametersEx == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_Disconnect = (PLibMCDriver_EulerEulerConnection_DisconnectPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_disconnect");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_Disconnect = (PLibMCDriver_EulerEulerConnection_DisconnectPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_disconnect");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_Disconnect == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_GetIdentifier = (PLibMCDriver_EulerEulerConnection_GetIdentifierPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_getidentifier");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_GetIdentifier = (PLibMCDriver_EulerEulerConnection_GetIdentifierPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_getidentifier");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_GetIdentifier == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_GetApplicationName = (PLibMCDriver_EulerEulerConnection_GetApplicationNamePtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_getapplicationname");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_GetApplicationName = (PLibMCDriver_EulerEulerConnection_GetApplicationNamePtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_getapplicationname");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_GetApplicationName == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_GetApplicationVersion = (PLibMCDriver_EulerEulerConnection_GetApplicationVersionPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_getapplicationversion");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_GetApplicationVersion = (PLibMCDriver_EulerEulerConnection_GetApplicationVersionPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_getapplicationversion");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_GetApplicationVersion == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_GetBaseURL = (PLibMCDriver_EulerEulerConnection_GetBaseURLPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_getbaseurl");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_GetBaseURL = (PLibMCDriver_EulerEulerConnection_GetBaseURLPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_getbaseurl");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_GetBaseURL == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_GetAPIKey = (PLibMCDriver_EulerEulerConnection_GetAPIKeyPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_getapikey");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_GetAPIKey = (PLibMCDriver_EulerEulerConnection_GetAPIKeyPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_getapikey");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_GetAPIKey == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_GetDeviceID = (PLibMCDriver_EulerEulerConnection_GetDeviceIDPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_getdeviceid");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_GetDeviceID = (PLibMCDriver_EulerEulerConnection_GetDeviceIDPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_getdeviceid");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_GetDeviceID == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_StartHeartBeat = (PLibMCDriver_EulerEulerConnection_StartHeartBeatPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_startheartbeat");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_StartHeartBeat = (PLibMCDriver_EulerEulerConnection_StartHeartBeatPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_startheartbeat");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_StartHeartBeat == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_StopHeartBeat = (PLibMCDriver_EulerEulerConnection_StopHeartBeatPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_stopheartbeat");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_StopHeartBeat = (PLibMCDriver_EulerEulerConnection_StopHeartBeatPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_stopheartbeat");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_StopHeartBeat == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_CreateBuild = (PLibMCDriver_EulerEulerConnection_CreateBuildPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_createbuild");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_CreateBuild = (PLibMCDriver_EulerEulerConnection_CreateBuildPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_createbuild");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_CreateBuild == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_UploadImage = (PLibMCDriver_EulerEulerConnection_UploadImagePtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_uploadimage");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_UploadImage = (PLibMCDriver_EulerEulerConnection_UploadImagePtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_uploadimage");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_UploadImage == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_EulerConnection_SetJobStatus = (PLibMCDriver_EulerEulerConnection_SetJobStatusPtr) GetProcAddress(hLibrary, "libmcdriver_euler_eulerconnection_setjobstatus");
		#else // _WIN32
		pWrapperTable->m_EulerConnection_SetJobStatus = (PLibMCDriver_EulerEulerConnection_SetJobStatusPtr) dlsym(hLibrary, "libmcdriver_euler_eulerconnection_setjobstatus");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_EulerConnection_SetJobStatus == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_SetCustomSDKResource = (PLibMCDriver_EulerDriver_Euler_SetCustomSDKResourcePtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_setcustomsdkresource");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_SetCustomSDKResource = (PLibMCDriver_EulerDriver_Euler_SetCustomSDKResourcePtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_setcustomsdkresource");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_SetCustomSDKResource == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_SetApplicationDetails = (PLibMCDriver_EulerDriver_Euler_SetApplicationDetailsPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_setapplicationdetails");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_SetApplicationDetails = (PLibMCDriver_EulerDriver_Euler_SetApplicationDetailsPtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_setapplicationdetails");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_SetApplicationDetails == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_Connect = (PLibMCDriver_EulerDriver_Euler_ConnectPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_connect");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_Connect = (PLibMCDriver_EulerDriver_Euler_ConnectPtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_connect");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_Connect == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_ConnectWithLicenseData = (PLibMCDriver_EulerDriver_Euler_ConnectWithLicenseDataPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_connectwithlicensedata");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_ConnectWithLicenseData = (PLibMCDriver_EulerDriver_Euler_ConnectWithLicenseDataPtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_connectwithlicensedata");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_ConnectWithLicenseData == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_ConnectWithLicenseResource = (PLibMCDriver_EulerDriver_Euler_ConnectWithLicenseResourcePtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_connectwithlicenseresource");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_ConnectWithLicenseResource = (PLibMCDriver_EulerDriver_Euler_ConnectWithLicenseResourcePtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_connectwithlicenseresource");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_ConnectWithLicenseResource == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_FindConnection = (PLibMCDriver_EulerDriver_Euler_FindConnectionPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_findconnection");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_FindConnection = (PLibMCDriver_EulerDriver_Euler_FindConnectionPtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_findconnection");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_FindConnection == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_ConnectionExists = (PLibMCDriver_EulerDriver_Euler_ConnectionExistsPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_connectionexists");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_ConnectionExists = (PLibMCDriver_EulerDriver_Euler_ConnectionExistsPtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_connectionexists");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_ConnectionExists == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_Driver_Euler_CloseAllConnections = (PLibMCDriver_EulerDriver_Euler_CloseAllConnectionsPtr) GetProcAddress(hLibrary, "libmcdriver_euler_driver_euler_closeallconnections");
		#else // _WIN32
		pWrapperTable->m_Driver_Euler_CloseAllConnections = (PLibMCDriver_EulerDriver_Euler_CloseAllConnectionsPtr) dlsym(hLibrary, "libmcdriver_euler_driver_euler_closeallconnections");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_Driver_Euler_CloseAllConnections == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_GetVersion = (PLibMCDriver_EulerGetVersionPtr) GetProcAddress(hLibrary, "libmcdriver_euler_getversion");
		#else // _WIN32
		pWrapperTable->m_GetVersion = (PLibMCDriver_EulerGetVersionPtr) dlsym(hLibrary, "libmcdriver_euler_getversion");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_GetVersion == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_GetLastError = (PLibMCDriver_EulerGetLastErrorPtr) GetProcAddress(hLibrary, "libmcdriver_euler_getlasterror");
		#else // _WIN32
		pWrapperTable->m_GetLastError = (PLibMCDriver_EulerGetLastErrorPtr) dlsym(hLibrary, "libmcdriver_euler_getlasterror");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_GetLastError == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_ReleaseInstance = (PLibMCDriver_EulerReleaseInstancePtr) GetProcAddress(hLibrary, "libmcdriver_euler_releaseinstance");
		#else // _WIN32
		pWrapperTable->m_ReleaseInstance = (PLibMCDriver_EulerReleaseInstancePtr) dlsym(hLibrary, "libmcdriver_euler_releaseinstance");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_ReleaseInstance == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_AcquireInstance = (PLibMCDriver_EulerAcquireInstancePtr) GetProcAddress(hLibrary, "libmcdriver_euler_acquireinstance");
		#else // _WIN32
		pWrapperTable->m_AcquireInstance = (PLibMCDriver_EulerAcquireInstancePtr) dlsym(hLibrary, "libmcdriver_euler_acquireinstance");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_AcquireInstance == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_InjectComponent = (PLibMCDriver_EulerInjectComponentPtr) GetProcAddress(hLibrary, "libmcdriver_euler_injectcomponent");
		#else // _WIN32
		pWrapperTable->m_InjectComponent = (PLibMCDriver_EulerInjectComponentPtr) dlsym(hLibrary, "libmcdriver_euler_injectcomponent");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_InjectComponent == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_GetSymbolLookupMethod = (PLibMCDriver_EulerGetSymbolLookupMethodPtr) GetProcAddress(hLibrary, "libmcdriver_euler_getsymbollookupmethod");
		#else // _WIN32
		pWrapperTable->m_GetSymbolLookupMethod = (PLibMCDriver_EulerGetSymbolLookupMethodPtr) dlsym(hLibrary, "libmcdriver_euler_getsymbollookupmethod");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_GetSymbolLookupMethod == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		#ifdef _WIN32
		pWrapperTable->m_CreateDriver = (PLibMCDriver_EulerCreateDriverPtr) GetProcAddress(hLibrary, "libmcdriver_euler_createdriver");
		#else // _WIN32
		pWrapperTable->m_CreateDriver = (PLibMCDriver_EulerCreateDriverPtr) dlsym(hLibrary, "libmcdriver_euler_createdriver");
		dlerror();
		#endif // _WIN32
		if (pWrapperTable->m_CreateDriver == nullptr)
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		pWrapperTable->m_LibraryHandle = hLibrary;
		return LIBMCDRIVER_EULER_SUCCESS;
	}

	inline LibMCDriver_EulerResult CWrapper::loadWrapperTableFromSymbolLookupMethod(sLibMCDriver_EulerDynamicWrapperTable * pWrapperTable, void* pSymbolLookupMethod)
{
		if (pWrapperTable == nullptr)
			return LIBMCDRIVER_EULER_ERROR_INVALIDPARAM;
		if (pSymbolLookupMethod == nullptr)
			return LIBMCDRIVER_EULER_ERROR_INVALIDPARAM;
		
		typedef LibMCDriver_EulerResult(*SymbolLookupType)(const char*, void**);
		
		SymbolLookupType pLookup = (SymbolLookupType)pSymbolLookupMethod;
		
		LibMCDriver_EulerResult eLookupError = LIBMCDRIVER_EULER_SUCCESS;
		eLookupError = (*pLookup)("libmcdriver_euler_driver_configure", (void**)&(pWrapperTable->m_Driver_Configure));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Configure == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_getname", (void**)&(pWrapperTable->m_Driver_GetName));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_GetName == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_gettype", (void**)&(pWrapperTable->m_Driver_GetType));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_GetType == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_getversion", (void**)&(pWrapperTable->m_Driver_GetVersion));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_GetVersion == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_queryparameters", (void**)&(pWrapperTable->m_Driver_QueryParameters));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_QueryParameters == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_queryparametersex", (void**)&(pWrapperTable->m_Driver_QueryParametersEx));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_QueryParametersEx == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_disconnect", (void**)&(pWrapperTable->m_EulerConnection_Disconnect));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_Disconnect == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_getidentifier", (void**)&(pWrapperTable->m_EulerConnection_GetIdentifier));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_GetIdentifier == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_getapplicationname", (void**)&(pWrapperTable->m_EulerConnection_GetApplicationName));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_GetApplicationName == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_getapplicationversion", (void**)&(pWrapperTable->m_EulerConnection_GetApplicationVersion));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_GetApplicationVersion == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_getbaseurl", (void**)&(pWrapperTable->m_EulerConnection_GetBaseURL));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_GetBaseURL == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_getapikey", (void**)&(pWrapperTable->m_EulerConnection_GetAPIKey));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_GetAPIKey == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_getdeviceid", (void**)&(pWrapperTable->m_EulerConnection_GetDeviceID));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_GetDeviceID == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_startheartbeat", (void**)&(pWrapperTable->m_EulerConnection_StartHeartBeat));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_StartHeartBeat == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_stopheartbeat", (void**)&(pWrapperTable->m_EulerConnection_StopHeartBeat));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_StopHeartBeat == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_createbuild", (void**)&(pWrapperTable->m_EulerConnection_CreateBuild));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_CreateBuild == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_uploadimage", (void**)&(pWrapperTable->m_EulerConnection_UploadImage));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_UploadImage == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_eulerconnection_setjobstatus", (void**)&(pWrapperTable->m_EulerConnection_SetJobStatus));
		if ( (eLookupError != 0) || (pWrapperTable->m_EulerConnection_SetJobStatus == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_setcustomsdkresource", (void**)&(pWrapperTable->m_Driver_Euler_SetCustomSDKResource));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_SetCustomSDKResource == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_setapplicationdetails", (void**)&(pWrapperTable->m_Driver_Euler_SetApplicationDetails));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_SetApplicationDetails == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_connect", (void**)&(pWrapperTable->m_Driver_Euler_Connect));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_Connect == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_connectwithlicensedata", (void**)&(pWrapperTable->m_Driver_Euler_ConnectWithLicenseData));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_ConnectWithLicenseData == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_connectwithlicenseresource", (void**)&(pWrapperTable->m_Driver_Euler_ConnectWithLicenseResource));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_ConnectWithLicenseResource == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_findconnection", (void**)&(pWrapperTable->m_Driver_Euler_FindConnection));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_FindConnection == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_connectionexists", (void**)&(pWrapperTable->m_Driver_Euler_ConnectionExists));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_ConnectionExists == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_driver_euler_closeallconnections", (void**)&(pWrapperTable->m_Driver_Euler_CloseAllConnections));
		if ( (eLookupError != 0) || (pWrapperTable->m_Driver_Euler_CloseAllConnections == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_getversion", (void**)&(pWrapperTable->m_GetVersion));
		if ( (eLookupError != 0) || (pWrapperTable->m_GetVersion == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_getlasterror", (void**)&(pWrapperTable->m_GetLastError));
		if ( (eLookupError != 0) || (pWrapperTable->m_GetLastError == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_releaseinstance", (void**)&(pWrapperTable->m_ReleaseInstance));
		if ( (eLookupError != 0) || (pWrapperTable->m_ReleaseInstance == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_acquireinstance", (void**)&(pWrapperTable->m_AcquireInstance));
		if ( (eLookupError != 0) || (pWrapperTable->m_AcquireInstance == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_injectcomponent", (void**)&(pWrapperTable->m_InjectComponent));
		if ( (eLookupError != 0) || (pWrapperTable->m_InjectComponent == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_getsymbollookupmethod", (void**)&(pWrapperTable->m_GetSymbolLookupMethod));
		if ( (eLookupError != 0) || (pWrapperTable->m_GetSymbolLookupMethod == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		eLookupError = (*pLookup)("libmcdriver_euler_createdriver", (void**)&(pWrapperTable->m_CreateDriver));
		if ( (eLookupError != 0) || (pWrapperTable->m_CreateDriver == nullptr) )
			return LIBMCDRIVER_EULER_ERROR_COULDNOTFINDLIBRARYEXPORT;
		
		return LIBMCDRIVER_EULER_SUCCESS;
}

	
	
	/**
	 * Method definitions for class CBase
	 */
	
	/**
	 * Method definitions for class CDriver
	 */
	
	/**
	* CDriver::Configure - Configures a driver with its specific configuration data.
	* @param[in] sConfigurationString - Configuration data of driver.
	*/
	void CDriver::Configure(const std::string & sConfigurationString)
	{
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Configure(m_pHandle, sConfigurationString.c_str()));
	}
	
	/**
	* CDriver::GetName - returns the name identifier of the driver
	* @return Name of the driver.
	*/
	std::string CDriver::GetName()
	{
		LibMCDriver_Euler_uint32 bytesNeededName = 0;
		LibMCDriver_Euler_uint32 bytesWrittenName = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_GetName(m_pHandle, 0, &bytesNeededName, nullptr));
		std::vector<char> bufferName(bytesNeededName);
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_GetName(m_pHandle, bytesNeededName, &bytesWrittenName, &bufferName[0]));
		
		return std::string(&bufferName[0]);
	}
	
	/**
	* CDriver::GetType - returns the type identifier of the driver
	* @return Type of the driver.
	*/
	std::string CDriver::GetType()
	{
		LibMCDriver_Euler_uint32 bytesNeededType = 0;
		LibMCDriver_Euler_uint32 bytesWrittenType = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_GetType(m_pHandle, 0, &bytesNeededType, nullptr));
		std::vector<char> bufferType(bytesNeededType);
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_GetType(m_pHandle, bytesNeededType, &bytesWrittenType, &bufferType[0]));
		
		return std::string(&bufferType[0]);
	}
	
	/**
	* CDriver::GetVersion - returns the version identifiers of the driver
	* @param[out] nMajor - Major version.
	* @param[out] nMinor - Minor version.
	* @param[out] nMicro - Micro version.
	* @param[out] sBuild - Build identifier.
	*/
	void CDriver::GetVersion(LibMCDriver_Euler_uint32 & nMajor, LibMCDriver_Euler_uint32 & nMinor, LibMCDriver_Euler_uint32 & nMicro, std::string & sBuild)
	{
		LibMCDriver_Euler_uint32 bytesNeededBuild = 0;
		LibMCDriver_Euler_uint32 bytesWrittenBuild = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_GetVersion(m_pHandle, &nMajor, &nMinor, &nMicro, 0, &bytesNeededBuild, nullptr));
		std::vector<char> bufferBuild(bytesNeededBuild);
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_GetVersion(m_pHandle, &nMajor, &nMinor, &nMicro, bytesNeededBuild, &bytesWrittenBuild, &bufferBuild[0]));
		sBuild = std::string(&bufferBuild[0]);
	}
	
	/**
	* CDriver::QueryParameters - Updates the driver parameters in the driver environment. Should only be called in the driver thread.
	*/
	void CDriver::QueryParameters()
	{
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_QueryParameters(m_pHandle));
	}
	
	/**
	* CDriver::QueryParametersEx - Updates the driver parameters in the driver environment. Might be called out of thread. Implementation MUST be able to handle parallel calls.
	* @param[in] pDriverUpdateInstance - Status update instance.
	*/
	void CDriver::QueryParametersEx(classParam<LibMCEnv::CDriverStatusUpdateSession> pDriverUpdateInstance)
	{
		LibMCEnvHandle hDriverUpdateInstance = pDriverUpdateInstance.GetHandle();
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_QueryParametersEx(m_pHandle, hDriverUpdateInstance));
	}
	
	/**
	 * Method definitions for class CEulerConnection
	 */
	
	/**
	* CEulerConnection::Disconnect - Disconnects the connection. No further call can be handled after.
	*/
	void CEulerConnection::Disconnect()
	{
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_Disconnect(m_pHandle));
	}
	
	/**
	* CEulerConnection::GetIdentifier - Returns the connection identifier.
	* @return Identifier of the connection.
	*/
	std::string CEulerConnection::GetIdentifier()
	{
		LibMCDriver_Euler_uint32 bytesNeededIdentifier = 0;
		LibMCDriver_Euler_uint32 bytesWrittenIdentifier = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetIdentifier(m_pHandle, 0, &bytesNeededIdentifier, nullptr));
		std::vector<char> bufferIdentifier(bytesNeededIdentifier);
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetIdentifier(m_pHandle, bytesNeededIdentifier, &bytesWrittenIdentifier, &bufferIdentifier[0]));
		
		return std::string(&bufferIdentifier[0]);
	}
	
	/**
	* CEulerConnection::GetApplicationName - Returns the application name.
	* @return Application Name in use.
	*/
	std::string CEulerConnection::GetApplicationName()
	{
		LibMCDriver_Euler_uint32 bytesNeededApplicationName = 0;
		LibMCDriver_Euler_uint32 bytesWrittenApplicationName = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetApplicationName(m_pHandle, 0, &bytesNeededApplicationName, nullptr));
		std::vector<char> bufferApplicationName(bytesNeededApplicationName);
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetApplicationName(m_pHandle, bytesNeededApplicationName, &bytesWrittenApplicationName, &bufferApplicationName[0]));
		
		return std::string(&bufferApplicationName[0]);
	}
	
	/**
	* CEulerConnection::GetApplicationVersion - Returns the application version.
	* @return Application Version in use.
	*/
	std::string CEulerConnection::GetApplicationVersion()
	{
		LibMCDriver_Euler_uint32 bytesNeededApplicationVersion = 0;
		LibMCDriver_Euler_uint32 bytesWrittenApplicationVersion = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetApplicationVersion(m_pHandle, 0, &bytesNeededApplicationVersion, nullptr));
		std::vector<char> bufferApplicationVersion(bytesNeededApplicationVersion);
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetApplicationVersion(m_pHandle, bytesNeededApplicationVersion, &bytesWrittenApplicationVersion, &bufferApplicationVersion[0]));
		
		return std::string(&bufferApplicationVersion[0]);
	}
	
	/**
	* CEulerConnection::GetBaseURL - Returns the base URL.
	* @return Base URL in use.
	*/
	std::string CEulerConnection::GetBaseURL()
	{
		LibMCDriver_Euler_uint32 bytesNeededBaseURL = 0;
		LibMCDriver_Euler_uint32 bytesWrittenBaseURL = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetBaseURL(m_pHandle, 0, &bytesNeededBaseURL, nullptr));
		std::vector<char> bufferBaseURL(bytesNeededBaseURL);
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetBaseURL(m_pHandle, bytesNeededBaseURL, &bytesWrittenBaseURL, &bufferBaseURL[0]));
		
		return std::string(&bufferBaseURL[0]);
	}
	
	/**
	* CEulerConnection::GetAPIKey - Returns the API Key.
	* @return API Key in use.
	*/
	std::string CEulerConnection::GetAPIKey()
	{
		LibMCDriver_Euler_uint32 bytesNeededAPIKey = 0;
		LibMCDriver_Euler_uint32 bytesWrittenAPIKey = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetAPIKey(m_pHandle, 0, &bytesNeededAPIKey, nullptr));
		std::vector<char> bufferAPIKey(bytesNeededAPIKey);
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetAPIKey(m_pHandle, bytesNeededAPIKey, &bytesWrittenAPIKey, &bufferAPIKey[0]));
		
		return std::string(&bufferAPIKey[0]);
	}
	
	/**
	* CEulerConnection::GetDeviceID - Returns the DeviceID.
	* @return DeviceID in use.
	*/
	std::string CEulerConnection::GetDeviceID()
	{
		LibMCDriver_Euler_uint32 bytesNeededDeviceID = 0;
		LibMCDriver_Euler_uint32 bytesWrittenDeviceID = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetDeviceID(m_pHandle, 0, &bytesNeededDeviceID, nullptr));
		std::vector<char> bufferDeviceID(bytesNeededDeviceID);
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_GetDeviceID(m_pHandle, bytesNeededDeviceID, &bytesWrittenDeviceID, &bufferDeviceID[0]));
		
		return std::string(&bufferDeviceID[0]);
	}
	
	/**
	* CEulerConnection::StartHeartBeat - Starts the heartbeat.
	*/
	void CEulerConnection::StartHeartBeat()
	{
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_StartHeartBeat(m_pHandle));
	}
	
	/**
	* CEulerConnection::StopHeartBeat - Stops the heartbeat.
	*/
	void CEulerConnection::StopHeartBeat()
	{
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_StopHeartBeat(m_pHandle));
	}
	
	/**
	* CEulerConnection::CreateBuild - Creates a new build job.
	* @param[in] sJobName - BuildJob Name
	* @param[in] nLayerCount - Layer Count
	* @return New BuildJob ID
	*/
	std::string CEulerConnection::CreateBuild(const std::string & sJobName, const LibMCDriver_Euler_uint32 nLayerCount)
	{
		LibMCDriver_Euler_uint32 bytesNeededBuildJobID = 0;
		LibMCDriver_Euler_uint32 bytesWrittenBuildJobID = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_CreateBuild(m_pHandle, sJobName.c_str(), nLayerCount, 0, &bytesNeededBuildJobID, nullptr));
		std::vector<char> bufferBuildJobID(bytesNeededBuildJobID);
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_CreateBuild(m_pHandle, sJobName.c_str(), nLayerCount, bytesNeededBuildJobID, &bytesWrittenBuildJobID, &bufferBuildJobID[0]));
		
		return std::string(&bufferBuildJobID[0]);
	}
	
	/**
	* CEulerConnection::UploadImage - Uploads an image to a build job.
	* @param[in] sBuildJobID - BuildJob ID
	* @param[in] nLayerIndex - Layer Index
	* @param[in] eImageType - Image Type
	* @param[in] pImage - Image Instance
	*/
	void CEulerConnection::UploadImage(const std::string & sBuildJobID, const LibMCDriver_Euler_uint32 nLayerIndex, const eEulerImageType eImageType, classParam<LibMCEnv::CImageData> pImage)
	{
		LibMCEnvHandle hImage = pImage.GetHandle();
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_UploadImage(m_pHandle, sBuildJobID.c_str(), nLayerIndex, eImageType, hImage));
	}
	
	/**
	* CEulerConnection::SetJobStatus - Updates a Job's status
	* @param[in] sBuildJobID - BuildJob ID
	* @param[in] eJobStatus - New Job Status
	*/
	void CEulerConnection::SetJobStatus(const std::string & sBuildJobID, const eEulerJobStatus eJobStatus)
	{
		CheckError(m_pWrapper->m_WrapperTable.m_EulerConnection_SetJobStatus(m_pHandle, sBuildJobID.c_str(), eJobStatus));
	}
	
	/**
	 * Method definitions for class CDriver_Euler
	 */
	
	/**
	* CDriver_Euler::SetCustomSDKResource - Sets the machine resource name of the LibEuler SDK to load. MUST be called before Connect or it has no effect.
	* @param[in] sResourceName - Resource name of core machine package. Empty means standard naming applies.
	*/
	void CDriver_Euler::SetCustomSDKResource(const std::string & sResourceName)
	{
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_SetCustomSDKResource(m_pHandle, sResourceName.c_str()));
	}
	
	/**
	* CDriver_Euler::SetApplicationDetails - Sets the application details. Will be used for subsequent connections.
	* @param[in] sApplicationName - Application Name to use.
	* @param[in] sApplicationVersion - Application Version to use.
	*/
	void CDriver_Euler::SetApplicationDetails(const std::string & sApplicationName, const std::string & sApplicationVersion)
	{
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_SetApplicationDetails(m_pHandle, sApplicationName.c_str(), sApplicationVersion.c_str()));
	}
	
	/**
	* CDriver_Euler::Connect - Creates a Euler Connection.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @param[in] sBaseURL - BaseURL to use.
	* @param[in] sAPIKey - API Key to use.
	* @param[in] sDeviceID - Device ID to use.
	* @return Euler Connection Instance.
	*/
	PEulerConnection CDriver_Euler::Connect(const std::string & sIdentifier, const std::string & sBaseURL, const std::string & sAPIKey, const std::string & sDeviceID)
	{
		LibMCDriver_EulerHandle hConnection = nullptr;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_Connect(m_pHandle, sIdentifier.c_str(), sBaseURL.c_str(), sAPIKey.c_str(), sDeviceID.c_str(), &hConnection));
		
		if (!hConnection) {
			CheckError(LIBMCDRIVER_EULER_ERROR_INVALIDPARAM);
		}
		return std::make_shared<CEulerConnection>(m_pWrapper, hConnection);
	}
	
	/**
	* CDriver_Euler::ConnectWithLicenseData - Creates a Euler Connection from a license file data.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @param[in] LicenseDataBuffer - License Data file to use.
	* @param[in] sDeviceID - Device ID to use.
	* @return Euler Connection Instance.
	*/
	PEulerConnection CDriver_Euler::ConnectWithLicenseData(const std::string & sIdentifier, const CInputVector<LibMCDriver_Euler_uint8> & LicenseDataBuffer, const std::string & sDeviceID)
	{
		LibMCDriver_EulerHandle hConnection = nullptr;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_ConnectWithLicenseData(m_pHandle, sIdentifier.c_str(), (LibMCDriver_Euler_uint64)LicenseDataBuffer.size(), LicenseDataBuffer.data(), sDeviceID.c_str(), &hConnection));
		
		if (!hConnection) {
			CheckError(LIBMCDRIVER_EULER_ERROR_INVALIDPARAM);
		}
		return std::make_shared<CEulerConnection>(m_pWrapper, hConnection);
	}
	
	/**
	* CDriver_Euler::ConnectWithLicenseResource - Creates a Euler Connection from a license file resource.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @param[in] sLicenseResourceName - License Data resource to use.
	* @param[in] sDeviceID - Device ID to use.
	* @return Euler Connection Instance.
	*/
	PEulerConnection CDriver_Euler::ConnectWithLicenseResource(const std::string & sIdentifier, const std::string & sLicenseResourceName, const std::string & sDeviceID)
	{
		LibMCDriver_EulerHandle hConnection = nullptr;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_ConnectWithLicenseResource(m_pHandle, sIdentifier.c_str(), sLicenseResourceName.c_str(), sDeviceID.c_str(), &hConnection));
		
		if (!hConnection) {
			CheckError(LIBMCDRIVER_EULER_ERROR_INVALIDPARAM);
		}
		return std::make_shared<CEulerConnection>(m_pWrapper, hConnection);
	}
	
	/**
	* CDriver_Euler::FindConnection - Finds a connection. Fails if connection does not exist.
	* @param[in] sIdentifier - Identifier for the connection. Fails if identifier is already existing.
	* @return Euler Connection Instance.
	*/
	PEulerConnection CDriver_Euler::FindConnection(const std::string & sIdentifier)
	{
		LibMCDriver_EulerHandle hConnection = nullptr;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_FindConnection(m_pHandle, sIdentifier.c_str(), &hConnection));
		
		if (!hConnection) {
			CheckError(LIBMCDRIVER_EULER_ERROR_INVALIDPARAM);
		}
		return std::make_shared<CEulerConnection>(m_pWrapper, hConnection);
	}
	
	/**
	* CDriver_Euler::ConnectionExists - Checks if a connection exists with a certain identifier.
	* @param[in] sIdentifier - Identifier for the connection.
	* @return Returns true, if the connection exists, false otherwise.
	*/
	bool CDriver_Euler::ConnectionExists(const std::string & sIdentifier)
	{
		bool resultExists = 0;
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_ConnectionExists(m_pHandle, sIdentifier.c_str(), &resultExists));
		
		return resultExists;
	}
	
	/**
	* CDriver_Euler::CloseAllConnections - Closes all connections.
	*/
	void CDriver_Euler::CloseAllConnections()
	{
		CheckError(m_pWrapper->m_WrapperTable.m_Driver_Euler_CloseAllConnections(m_pHandle));
	}

} // namespace LibMCDriver_Euler

#endif // __LIBMCDRIVER_EULER_CPPHEADER_DYNAMIC_CPP

