on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_linux_x64:
    runs-on: ubuntu-latest
    name: Build Linux x86-64 binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run buildscript in docker
        uses: ./.github/build-linux-x64
        id: build
        with:
          buildscript: './build_clean.sh'

  build_win_x64:
    runs-on: windows-latest
    name: Build Windows x86-64 Binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install MSVC C++ compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.2x.yyyyy
      - name: Install Nodejs 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Run build_clean.bat
        shell: cmd
        run: call build_clean.bat NOPAUSE
