on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_linux_x64:
    runs-on: ubuntu-latest
    name: Build binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run buildscript in docker
        uses: ./.github/build-linux-x64
        id: build
        with:
          buildscript: './build_clean.sh'